<?php

namespace OxidProfessionalServices\PayPal\Api\Model\Catalog;

use JsonSerializable;
use OxidProfessionalServices\PayPal\Api\Model\BaseModel;

/**
 * The create product request details.
 */
class ProductRequestPOST implements JsonSerializable
{
    use BaseModel;

    const CATEGORY_AC_REFRIGERATION_REPAIR = 'AC_REFRIGERATION_REPAIR';
    const CATEGORY_ACADEMIC_SOFTWARE = 'ACADEMIC_SOFTWARE';
    const CATEGORY_ACCESSORIES = 'ACCESSORIES';
    const CATEGORY_ACCOUNTING = 'ACCOUNTING';
    const CATEGORY_ADULT = 'ADULT';
    const CATEGORY_ADVERTISING = 'ADVERTISING';
    const CATEGORY_AFFILIATED_AUTO_RENTAL = 'AFFILIATED_AUTO_RENTAL';
    const CATEGORY_AGENCIES = 'AGENCIES';
    const CATEGORY_AGGREGATORS = 'AGGREGATORS';
    const CATEGORY_AGRICULTURAL_COOPERATIVE_FOR_MAIL_ORDER = 'AGRICULTURAL_COOPERATIVE_FOR_MAIL_ORDER';
    const CATEGORY_AIR_CARRIERS_AIRLINES = 'AIR_CARRIERS_AIRLINES';
    const CATEGORY_AIRLINES = 'AIRLINES';
    const CATEGORY_AIRPORTS_FLYING_FIELDS = 'AIRPORTS_FLYING_FIELDS';
    const CATEGORY_ALCOHOLIC_BEVERAGES = 'ALCOHOLIC_BEVERAGES';
    const CATEGORY_AMUSEMENT_PARKS_CARNIVALS = 'AMUSEMENT_PARKS_CARNIVALS';
    const CATEGORY_ANIMATION = 'ANIMATION';
    const CATEGORY_ANTIQUES = 'ANTIQUES';
    const CATEGORY_APPLIANCES = 'APPLIANCES';
    const CATEGORY_AQUARIAMS_SEAQUARIUMS_DOLPHINARIUMS = 'AQUARIAMS_SEAQUARIUMS_DOLPHINARIUMS';
    const CATEGORY_ARCHITECTURAL_ENGINEERING_AND_SURVEYING_SERVICES = 'ARCHITECTURAL_ENGINEERING_AND_SURVEYING_SERVICES';
    const CATEGORY_ART_AND_CRAFT_SUPPLIES = 'ART_AND_CRAFT_SUPPLIES';
    const CATEGORY_ART_DEALERS_AND_GALLERIES = 'ART_DEALERS_AND_GALLERIES';
    const CATEGORY_ARTIFACTS_GRAVE_RELATED_AND_NATIVE_AMERICAN_CRAFTS = 'ARTIFACTS_GRAVE_RELATED_AND_NATIVE_AMERICAN_CRAFTS';
    const CATEGORY_ARTS_AND_CRAFTS = 'ARTS_AND_CRAFTS';
    const CATEGORY_ARTS_CRAFTS_AND_COLLECTIBLES = 'ARTS_CRAFTS_AND_COLLECTIBLES';
    const CATEGORY_AUDIO_BOOKS = 'AUDIO_BOOKS';
    const CATEGORY_AUTO_ASSOCIATIONS_CLUBS = 'AUTO_ASSOCIATIONS_CLUBS';
    const CATEGORY_AUTO_DEALER_USED_ONLY = 'AUTO_DEALER_USED_ONLY';
    const CATEGORY_AUTO_RENTALS = 'AUTO_RENTALS';
    const CATEGORY_AUTO_SERVICE = 'AUTO_SERVICE';
    const CATEGORY_AUTOMATED_FUEL_DISPENSERS = 'AUTOMATED_FUEL_DISPENSERS';
    const CATEGORY_AUTOMOBILE_ASSOCIATIONS = 'AUTOMOBILE_ASSOCIATIONS';
    const CATEGORY_AUTOMOTIVE = 'AUTOMOTIVE';
    const CATEGORY_AUTOMOTIVE_REPAIR_SHOPS_NON_DEALER = 'AUTOMOTIVE_REPAIR_SHOPS_NON_DEALER';
    const CATEGORY_AUTOMOTIVE_TOP_AND_BODY_SHOPS = 'AUTOMOTIVE_TOP_AND_BODY_SHOPS';
    const CATEGORY_AVIATION = 'AVIATION';
    const CATEGORY_BABIES_CLOTHING_AND_SUPPLIES = 'BABIES_CLOTHING_AND_SUPPLIES';
    const CATEGORY_BABY = 'BABY';
    const CATEGORY_BANDS_ORCHESTRAS_ENTERTAINERS = 'BANDS_ORCHESTRAS_ENTERTAINERS';
    const CATEGORY_BARBIES = 'BARBIES';
    const CATEGORY_BATH_AND_BODY = 'BATH_AND_BODY';
    const CATEGORY_BATTERIES = 'BATTERIES';
    const CATEGORY_BEAN_BABIES = 'BEAN_BABIES';
    const CATEGORY_BEAUTY = 'BEAUTY';
    const CATEGORY_BEAUTY_AND_FRAGRANCES = 'BEAUTY_AND_FRAGRANCES';
    const CATEGORY_BED_AND_BATH = 'BED_AND_BATH';
    const CATEGORY_BICYCLE_SHOPS_SALES_AND_SERVICE = 'BICYCLE_SHOPS_SALES_AND_SERVICE';
    const CATEGORY_BICYCLES_AND_ACCESSORIES = 'BICYCLES_AND_ACCESSORIES';
    const CATEGORY_BILLIARD_POOL_ESTABLISHMENTS = 'BILLIARD_POOL_ESTABLISHMENTS';
    const CATEGORY_BOAT_DEALERS = 'BOAT_DEALERS';
    const CATEGORY_BOAT_RENTALS_AND_LEASING = 'BOAT_RENTALS_AND_LEASING';
    const CATEGORY_BOATING_SAILING_AND_ACCESSORIES = 'BOATING_SAILING_AND_ACCESSORIES';
    const CATEGORY_BOOKS = 'BOOKS';
    const CATEGORY_BOOKS_AND_MAGAZINES = 'BOOKS_AND_MAGAZINES';
    const CATEGORY_BOOKS_MANUSCRIPTS = 'BOOKS_MANUSCRIPTS';
    const CATEGORY_BOOKS_PERIODICALS_AND_NEWSPAPERS = 'BOOKS_PERIODICALS_AND_NEWSPAPERS';
    const CATEGORY_BOWLING_ALLEYS = 'BOWLING_ALLEYS';
    const CATEGORY_BULLETIN_BOARD = 'BULLETIN_BOARD';
    const CATEGORY_BUS_LINE = 'BUS_LINE';
    const CATEGORY_BUS_LINES_CHARTERS_TOUR_BUSES = 'BUS_LINES_CHARTERS_TOUR_BUSES';
    const CATEGORY_BUSINESS = 'BUSINESS';
    const CATEGORY_BUSINESS_AND_SECRETARIAL_SCHOOLS = 'BUSINESS_AND_SECRETARIAL_SCHOOLS';
    const CATEGORY_BUYING_AND_SHOPPING_SERVICES_AND_CLUBS = 'BUYING_AND_SHOPPING_SERVICES_AND_CLUBS';
    const CATEGORY_CABLE_SATELLITE_AND_OTHER_PAY_TELEVISION_AND_RADIO_SERVICES = 'CABLE_SATELLITE_AND_OTHER_PAY_TELEVISION_AND_RADIO_SERVICES';
    const CATEGORY_CABLE_SATELLITE_AND_OTHER_PAY_TV_AND_RADIO = 'CABLE_SATELLITE_AND_OTHER_PAY_TV_AND_RADIO';
    const CATEGORY_CAMERA_AND_PHOTOGRAPHIC_SUPPLIES = 'CAMERA_AND_PHOTOGRAPHIC_SUPPLIES';
    const CATEGORY_CAMERAS = 'CAMERAS';
    const CATEGORY_CAMERAS_AND_PHOTOGRAPHY = 'CAMERAS_AND_PHOTOGRAPHY';
    const CATEGORY_CAMPER_RECREATIONAL_AND_UTILITY_TRAILER_DEALERS = 'CAMPER_RECREATIONAL_AND_UTILITY_TRAILER_DEALERS';
    const CATEGORY_CAMPING_AND_OUTDOORS = 'CAMPING_AND_OUTDOORS';
    const CATEGORY_CAMPING_AND_SURVIVAL = 'CAMPING_AND_SURVIVAL';
    const CATEGORY_CAR_AND_TRUCK_DEALERS = 'CAR_AND_TRUCK_DEALERS';
    const CATEGORY_CAR_AND_TRUCK_DEALERS_USED_ONLY = 'CAR_AND_TRUCK_DEALERS_USED_ONLY';
    const CATEGORY_CAR_AUDIO_AND_ELECTRONICS = 'CAR_AUDIO_AND_ELECTRONICS';
    const CATEGORY_CAR_RENTAL_AGENCY = 'CAR_RENTAL_AGENCY';
    const CATEGORY_CATALOG_MERCHANT = 'CATALOG_MERCHANT';
    const CATEGORY_CATALOG_RETAIL_MERCHANT = 'CATALOG_RETAIL_MERCHANT';
    const CATEGORY_CATERING_SERVICES = 'CATERING_SERVICES';
    const CATEGORY_CHARITY = 'CHARITY';
    const CATEGORY_CHECK_CASHIER = 'CHECK_CASHIER';
    const CATEGORY_CHILD_CARE_SERVICES = 'CHILD_CARE_SERVICES';
    const CATEGORY_CHILDREN_BOOKS = 'CHILDREN_BOOKS';
    const CATEGORY_CHIROPODISTS_PODIATRISTS = 'CHIROPODISTS_PODIATRISTS';
    const CATEGORY_CHIROPRACTORS = 'CHIROPRACTORS';
    const CATEGORY_CIGAR_STORES_AND_STANDS = 'CIGAR_STORES_AND_STANDS';
    const CATEGORY_CIVIC_SOCIAL_FRATERNAL_ASSOCIATIONS = 'CIVIC_SOCIAL_FRATERNAL_ASSOCIATIONS';
    const CATEGORY_CIVIL_SOCIAL_FRAT_ASSOCIATIONS = 'CIVIL_SOCIAL_FRAT_ASSOCIATIONS';
    const CATEGORY_CLOTHING = 'CLOTHING';
    const CATEGORY_CLOTHING_ACCESSORIES_AND_SHOES = 'CLOTHING_ACCESSORIES_AND_SHOES';
    const CATEGORY_CLOTHING_RENTAL = 'CLOTHING_RENTAL';
    const CATEGORY_COFFEE_AND_TEA = 'COFFEE_AND_TEA';
    const CATEGORY_COIN_OPERATED_BANKS_AND_CASINOS = 'COIN_OPERATED_BANKS_AND_CASINOS';
    const CATEGORY_COLLECTIBLES = 'COLLECTIBLES';
    const CATEGORY_COLLECTION_AGENCY = 'COLLECTION_AGENCY';
    const CATEGORY_COLLEGES_AND_UNIVERSITIES = 'COLLEGES_AND_UNIVERSITIES';
    const CATEGORY_COMMERCIAL_EQUIPMENT = 'COMMERCIAL_EQUIPMENT';
    const CATEGORY_COMMERCIAL_FOOTWEAR = 'COMMERCIAL_FOOTWEAR';
    const CATEGORY_COMMERCIAL_PHOTOGRAPHY = 'COMMERCIAL_PHOTOGRAPHY';
    const CATEGORY_COMMERCIAL_PHOTOGRAPHY_ART_AND_GRAPHICS = 'COMMERCIAL_PHOTOGRAPHY_ART_AND_GRAPHICS';
    const CATEGORY_COMMERCIAL_SPORTS_PROFESSIONA = 'COMMERCIAL_SPORTS_PROFESSIONA';
    const CATEGORY_COMMODITIES_AND_FUTURES_EXCHANGE = 'COMMODITIES_AND_FUTURES_EXCHANGE';
    const CATEGORY_COMPUTER_AND_DATA_PROCESSING_SERVICES = 'COMPUTER_AND_DATA_PROCESSING_SERVICES';
    const CATEGORY_COMPUTER_HARDWARE_AND_SOFTWARE = 'COMPUTER_HARDWARE_AND_SOFTWARE';
    const CATEGORY_COMPUTER_MAINTENANCE_REPAIR_AND_SERVICES_NOT_ELSEWHERE_CLAS = 'COMPUTER_MAINTENANCE_REPAIR_AND_SERVICES_NOT_ELSEWHERE_CLAS';
    const CATEGORY_CONSTRUCTION = 'CONSTRUCTION';
    const CATEGORY_CONSTRUCTION_MATERIALS_NOT_ELSEWHERE_CLASSIFIED = 'CONSTRUCTION_MATERIALS_NOT_ELSEWHERE_CLASSIFIED';
    const CATEGORY_CONSULTING_SERVICES = 'CONSULTING_SERVICES';
    const CATEGORY_CONSUMER_CREDIT_REPORTING_AGENCIES = 'CONSUMER_CREDIT_REPORTING_AGENCIES';
    const CATEGORY_CONVALESCENT_HOMES = 'CONVALESCENT_HOMES';
    const CATEGORY_COSMETIC_STORES = 'COSMETIC_STORES';
    const CATEGORY_COUNSELING_SERVICES_DEBT_MARRIAGE_PERSONAL = 'COUNSELING_SERVICES_DEBT_MARRIAGE_PERSONAL';
    const CATEGORY_COUNTERFEIT_CURRENCY_AND_STAMPS = 'COUNTERFEIT_CURRENCY_AND_STAMPS';
    const CATEGORY_COUNTERFEIT_ITEMS = 'COUNTERFEIT_ITEMS';
    const CATEGORY_COUNTRY_CLUBS = 'COUNTRY_CLUBS';
    const CATEGORY_COURIER_SERVICES = 'COURIER_SERVICES';
    const CATEGORY_COURIER_SERVICES_AIR_AND_GROUND_AND_FREIGHT_FORWARDERS = 'COURIER_SERVICES_AIR_AND_GROUND_AND_FREIGHT_FORWARDERS';
    const CATEGORY_COURT_COSTS_ALIMNY_CHILD_SUPT = 'COURT_COSTS_ALIMNY_CHILD_SUPT';
    const CATEGORY_COURT_COSTS_INCLUDING_ALIMONY_AND_CHILD_SUPPORT_COURTS_OF_LAW = 'COURT_COSTS_INCLUDING_ALIMONY_AND_CHILD_SUPPORT_COURTS_OF_LAW';
    const CATEGORY_CREDIT_CARDS = 'CREDIT_CARDS';
    const CATEGORY_CREDIT_UNION = 'CREDIT_UNION';
    const CATEGORY_CULTURE_AND_RELIGION = 'CULTURE_AND_RELIGION';
    const CATEGORY_DAIRY_PRODUCTS_STORES = 'DAIRY_PRODUCTS_STORES';
    const CATEGORY_DANCE_HALLS_STUDIOS_AND_SCHOOLS = 'DANCE_HALLS_STUDIOS_AND_SCHOOLS';
    const CATEGORY_DECORATIVE = 'DECORATIVE';
    const CATEGORY_DENTAL = 'DENTAL';
    const CATEGORY_DENTISTS_AND_ORTHODONTISTS = 'DENTISTS_AND_ORTHODONTISTS';
    const CATEGORY_DEPARTMENT_STORES = 'DEPARTMENT_STORES';
    const CATEGORY_DESKTOP_PCS = 'DESKTOP_PCS';
    const CATEGORY_DEVICES = 'DEVICES';
    const CATEGORY_DIECAST_TOYS_VEHICLES = 'DIECAST_TOYS_VEHICLES';
    const CATEGORY_DIGITAL_GAMES = 'DIGITAL_GAMES';
    const CATEGORY_DIGITAL_MEDIA_BOOKS_MOVIES_MUSIC = 'DIGITAL_MEDIA_BOOKS_MOVIES_MUSIC';
    const CATEGORY_DIRECT_MARKETING = 'DIRECT_MARKETING';
    const CATEGORY_DIRECT_MARKETING_CATALOG_MERCHANT = 'DIRECT_MARKETING_CATALOG_MERCHANT';
    const CATEGORY_DIRECT_MARKETING_INBOUND_TELE = 'DIRECT_MARKETING_INBOUND_TELE';
    const CATEGORY_DIRECT_MARKETING_OUTBOUND_TELE = 'DIRECT_MARKETING_OUTBOUND_TELE';
    const CATEGORY_DIRECT_MARKETING_SUBSCRIPTION = 'DIRECT_MARKETING_SUBSCRIPTION';
    const CATEGORY_DISCOUNT_STORES = 'DISCOUNT_STORES';
    const CATEGORY_DOOR_TO_DOOR_SALES = 'DOOR_TO_DOOR_SALES';
    const CATEGORY_DRAPERY_WINDOW_COVERING_AND_UPHOLSTERY = 'DRAPERY_WINDOW_COVERING_AND_UPHOLSTERY';
    const CATEGORY_DRINKING_PLACES = 'DRINKING_PLACES';
    const CATEGORY_DRUGSTORE = 'DRUGSTORE';
    const CATEGORY_DURABLE_GOODS = 'DURABLE_GOODS';
    const CATEGORY_ECOMMERCE_DEVELOPMENT = 'ECOMMERCE_DEVELOPMENT';
    const CATEGORY_ECOMMERCE_SERVICES = 'ECOMMERCE_SERVICES';
    const CATEGORY_EDUCATIONAL_AND_TEXTBOOKS = 'EDUCATIONAL_AND_TEXTBOOKS';
    const CATEGORY_ELECTRIC_RAZOR_STORES = 'ELECTRIC_RAZOR_STORES';
    const CATEGORY_ELECTRICAL_AND_SMALL_APPLIANCE_REPAIR = 'ELECTRICAL_AND_SMALL_APPLIANCE_REPAIR';
    const CATEGORY_ELECTRICAL_CONTRACTORS = 'ELECTRICAL_CONTRACTORS';
    const CATEGORY_ELECTRICAL_PARTS_AND_EQUIPMENT = 'ELECTRICAL_PARTS_AND_EQUIPMENT';
    const CATEGORY_ELECTRONIC_CASH = 'ELECTRONIC_CASH';
    const CATEGORY_ELEMENTARY_AND_SECONDARY_SCHOOLS = 'ELEMENTARY_AND_SECONDARY_SCHOOLS';
    const CATEGORY_EMPLOYMENT = 'EMPLOYMENT';
    const CATEGORY_ENTERTAINERS = 'ENTERTAINERS';
    const CATEGORY_ENTERTAINMENT_AND_MEDIA = 'ENTERTAINMENT_AND_MEDIA';
    const CATEGORY_EQUIP_TOOL_FURNITURE_AND_APPLIANCE_RENTAL_AND_LEASING = 'EQUIP_TOOL_FURNITURE_AND_APPLIANCE_RENTAL_AND_LEASING';
    const CATEGORY_ESCROW = 'ESCROW';
    const CATEGORY_EVENT_AND_WEDDING_PLANNING = 'EVENT_AND_WEDDING_PLANNING';
    const CATEGORY_EXERCISE_AND_FITNESS = 'EXERCISE_AND_FITNESS';
    const CATEGORY_EXERCISE_EQUIPMENT = 'EXERCISE_EQUIPMENT';
    const CATEGORY_EXTERMINATING_AND_DISINFECTING_SERVICES = 'EXTERMINATING_AND_DISINFECTING_SERVICES';
    const CATEGORY_FABRICS_AND_SEWING = 'FABRICS_AND_SEWING';
    const CATEGORY_FAMILY_CLOTHING_STORES = 'FAMILY_CLOTHING_STORES';
    const CATEGORY_FASHION_JEWELRY = 'FASHION_JEWELRY';
    const CATEGORY_FAST_FOOD_RESTAURANTS = 'FAST_FOOD_RESTAURANTS';
    const CATEGORY_FICTION_AND_NONFICTION = 'FICTION_AND_NONFICTION';
    const CATEGORY_FINANCE_COMPANY = 'FINANCE_COMPANY';
    const CATEGORY_FINANCIAL_AND_INVESTMENT_ADVICE = 'FINANCIAL_AND_INVESTMENT_ADVICE';
    const CATEGORY_FINANCIAL_INSTITUTIONS_MERCHANDISE_AND_SERVICES = 'FINANCIAL_INSTITUTIONS_MERCHANDISE_AND_SERVICES';
    const CATEGORY_FIREARM_ACCESSORIES = 'FIREARM_ACCESSORIES';
    const CATEGORY_FIREARMS_WEAPONS_AND_KNIVES = 'FIREARMS_WEAPONS_AND_KNIVES';
    const CATEGORY_FIREPLACE_AND_FIREPLACE_SCREENS = 'FIREPLACE_AND_FIREPLACE_SCREENS';
    const CATEGORY_FIREWORKS = 'FIREWORKS';
    const CATEGORY_FISHING = 'FISHING';
    const CATEGORY_FLORISTS = 'FLORISTS';
    const CATEGORY_FLOWERS = 'FLOWERS';
    const CATEGORY_FOOD_DRINK_AND_NUTRITION = 'FOOD_DRINK_AND_NUTRITION';
    const CATEGORY_FOOD_PRODUCTS = 'FOOD_PRODUCTS';
    const CATEGORY_FOOD_RETAIL_AND_SERVICE = 'FOOD_RETAIL_AND_SERVICE';
    const CATEGORY_FRAGRANCES_AND_PERFUMES = 'FRAGRANCES_AND_PERFUMES';
    const CATEGORY_FREEZER_AND_LOCKER_MEAT_PROVISIONERS = 'FREEZER_AND_LOCKER_MEAT_PROVISIONERS';
    const CATEGORY_FUEL_DEALERS_FUEL_OIL_WOOD_AND_COAL = 'FUEL_DEALERS_FUEL_OIL_WOOD_AND_COAL';
    const CATEGORY_FUEL_DEALERS_NON_AUTOMOTIVE = 'FUEL_DEALERS_NON_AUTOMOTIVE';
    const CATEGORY_FUNERAL_SERVICES_AND_CREMATORIES = 'FUNERAL_SERVICES_AND_CREMATORIES';
    const CATEGORY_FURNISHING_AND_DECORATING = 'FURNISHING_AND_DECORATING';
    const CATEGORY_FURNITURE = 'FURNITURE';
    const CATEGORY_FURRIERS_AND_FUR_SHOPS = 'FURRIERS_AND_FUR_SHOPS';
    const CATEGORY_GADGETS_AND_OTHER_ELECTRONICS = 'GADGETS_AND_OTHER_ELECTRONICS';
    const CATEGORY_GAMBLING = 'GAMBLING';
    const CATEGORY_GAME_SOFTWARE = 'GAME_SOFTWARE';
    const CATEGORY_GAMES = 'GAMES';
    const CATEGORY_GARDEN_SUPPLIES = 'GARDEN_SUPPLIES';
    const CATEGORY_GENERAL = 'GENERAL';
    const CATEGORY_GENERAL_CONTRACTORS = 'GENERAL_CONTRACTORS';
    const CATEGORY_GENERAL_GOVERNMENT = 'GENERAL_GOVERNMENT';
    const CATEGORY_GENERAL_SOFTWARE = 'GENERAL_SOFTWARE';
    const CATEGORY_GENERAL_TELECOM = 'GENERAL_TELECOM';
    const CATEGORY_GIFTS_AND_FLOWERS = 'GIFTS_AND_FLOWERS';
    const CATEGORY_GLASS_PAINT_AND_WALLPAPER_STORES = 'GLASS_PAINT_AND_WALLPAPER_STORES';
    const CATEGORY_GLASSWARE_CRYSTAL_STORES = 'GLASSWARE_CRYSTAL_STORES';
    const CATEGORY_GOVERNMENT = 'GOVERNMENT';
    const CATEGORY_GOVERNMENT_IDS_AND_LICENSES = 'GOVERNMENT_IDS_AND_LICENSES';
    const CATEGORY_GOVERNMENT_LICENSED_ON_LINE_CASINOS_ON_LINE_GAMBLING = 'GOVERNMENT_LICENSED_ON_LINE_CASINOS_ON_LINE_GAMBLING';
    const CATEGORY_GOVERNMENT_OWNED_LOTTERIES = 'GOVERNMENT_OWNED_LOTTERIES';
    const CATEGORY_GOVERNMENT_SERVICES = 'GOVERNMENT_SERVICES';
    const CATEGORY_GRAPHIC_AND_COMMERCIAL_DESIGN = 'GRAPHIC_AND_COMMERCIAL_DESIGN';
    const CATEGORY_GREETING_CARDS = 'GREETING_CARDS';
    const CATEGORY_GROCERY_STORES_AND_SUPERMARKETS = 'GROCERY_STORES_AND_SUPERMARKETS';
    const CATEGORY_HARDWARE_AND_TOOLS = 'HARDWARE_AND_TOOLS';
    const CATEGORY_HARDWARE_EQUIPMENT_AND_SUPPLIES = 'HARDWARE_EQUIPMENT_AND_SUPPLIES';
    const CATEGORY_HAZARDOUS_RESTRICTED_AND_PERISHABLE_ITEMS = 'HAZARDOUS_RESTRICTED_AND_PERISHABLE_ITEMS';
    const CATEGORY_HEALTH_AND_BEAUTY_SPAS = 'HEALTH_AND_BEAUTY_SPAS';
    const CATEGORY_HEALTH_AND_NUTRITION = 'HEALTH_AND_NUTRITION';
    const CATEGORY_HEALTH_AND_PERSONAL_CARE = 'HEALTH_AND_PERSONAL_CARE';
    const CATEGORY_HEARING_AIDS_SALES_AND_SUPPLIES = 'HEARING_AIDS_SALES_AND_SUPPLIES';
    const CATEGORY_HEATING_PLUMBING_AC = 'HEATING_PLUMBING_AC';
    const CATEGORY_HIGH_RISK_MERCHANT = 'HIGH_RISK_MERCHANT';
    const CATEGORY_HIRING_SERVICES = 'HIRING_SERVICES';
    const CATEGORY_HOBBIES_TOYS_AND_GAMES = 'HOBBIES_TOYS_AND_GAMES';
    const CATEGORY_HOME_AND_GARDEN = 'HOME_AND_GARDEN';
    const CATEGORY_HOME_AUDIO = 'HOME_AUDIO';
    const CATEGORY_HOME_DECOR = 'HOME_DECOR';
    const CATEGORY_HOME_ELECTRONICS = 'HOME_ELECTRONICS';
    const CATEGORY_HOSPITALS = 'HOSPITALS';
    const CATEGORY_HOTELS_MOTELS_INNS_RESORTS = 'HOTELS_MOTELS_INNS_RESORTS';
    const CATEGORY_HOUSEWARES = 'HOUSEWARES';
    const CATEGORY_HUMAN_PARTS_AND_REMAINS = 'HUMAN_PARTS_AND_REMAINS';
    const CATEGORY_HUMOROUS_GIFTS_AND_NOVELTIES = 'HUMOROUS_GIFTS_AND_NOVELTIES';
    const CATEGORY_HUNTING = 'HUNTING';
    const CATEGORY_IDS_LICENSES_AND_PASSPORTS = 'IDS_LICENSES_AND_PASSPORTS';
    const CATEGORY_ILLEGAL_DRUGS_AND_PARAPHERNALIA = 'ILLEGAL_DRUGS_AND_PARAPHERNALIA';
    const CATEGORY_INDUSTRIAL = 'INDUSTRIAL';
    const CATEGORY_INDUSTRIAL_AND_MANUFACTURING_SUPPLIES = 'INDUSTRIAL_AND_MANUFACTURING_SUPPLIES';
    const CATEGORY_INSURANCE_AUTO_AND_HOME = 'INSURANCE_AUTO_AND_HOME';
    const CATEGORY_INSURANCE_DIRECT = 'INSURANCE_DIRECT';
    const CATEGORY_INSURANCE_LIFE_AND_ANNUITY = 'INSURANCE_LIFE_AND_ANNUITY';
    const CATEGORY_INSURANCE_SALES_UNDERWRITING = 'INSURANCE_SALES_UNDERWRITING';
    const CATEGORY_INSURANCE_UNDERWRITING_PREMIUMS = 'INSURANCE_UNDERWRITING_PREMIUMS';
    const CATEGORY_INTERNET_AND_NETWORK_SERVICES = 'INTERNET_AND_NETWORK_SERVICES';
    const CATEGORY_INTRA_COMPANY_PURCHASES = 'INTRA_COMPANY_PURCHASES';
    const CATEGORY_LABORATORIES_DENTAL_MEDICAL = 'LABORATORIES_DENTAL_MEDICAL';
    const CATEGORY_LANDSCAPING = 'LANDSCAPING';
    const CATEGORY_LANDSCAPING_AND_HORTICULTURAL_SERVICES = 'LANDSCAPING_AND_HORTICULTURAL_SERVICES';
    const CATEGORY_LAUNDRY_CLEANING_SERVICES = 'LAUNDRY_CLEANING_SERVICES';
    const CATEGORY_LEGAL = 'LEGAL';
    const CATEGORY_LEGAL_SERVICES_AND_ATTORNEYS = 'LEGAL_SERVICES_AND_ATTORNEYS';
    const CATEGORY_LOCAL_DELIVERY_SERVICE = 'LOCAL_DELIVERY_SERVICE';
    const CATEGORY_LOCKSMITH = 'LOCKSMITH';
    const CATEGORY_LODGING_AND_ACCOMMODATIONS = 'LODGING_AND_ACCOMMODATIONS';
    const CATEGORY_LOTTERY_AND_CONTESTS = 'LOTTERY_AND_CONTESTS';
    const CATEGORY_LUGGAGE_AND_LEATHER_GOODS = 'LUGGAGE_AND_LEATHER_GOODS';
    const CATEGORY_LUMBER_AND_BUILDING_MATERIALS = 'LUMBER_AND_BUILDING_MATERIALS';
    const CATEGORY_MAGAZINES = 'MAGAZINES';
    const CATEGORY_MAINTENANCE_AND_REPAIR_SERVICES = 'MAINTENANCE_AND_REPAIR_SERVICES';
    const CATEGORY_MAKEUP_AND_COSMETICS = 'MAKEUP_AND_COSMETICS';
    const CATEGORY_MANUAL_CASH_DISBURSEMENTS = 'MANUAL_CASH_DISBURSEMENTS';
    const CATEGORY_MASSAGE_PARLORS = 'MASSAGE_PARLORS';
    const CATEGORY_MEDICAL = 'MEDICAL';
    const CATEGORY_MEDICAL_AND_PHARMACEUTICAL = 'MEDICAL_AND_PHARMACEUTICAL';
    const CATEGORY_MEDICAL_CARE = 'MEDICAL_CARE';
    const CATEGORY_MEDICAL_EQUIPMENT_AND_SUPPLIES = 'MEDICAL_EQUIPMENT_AND_SUPPLIES';
    const CATEGORY_MEDICAL_SERVICES = 'MEDICAL_SERVICES';
    const CATEGORY_MEETING_PLANNERS = 'MEETING_PLANNERS';
    const CATEGORY_MEMBERSHIP_CLUBS_AND_ORGANIZATIONS = 'MEMBERSHIP_CLUBS_AND_ORGANIZATIONS';
    const CATEGORY_MEMBERSHIP_COUNTRY_CLUBS_GOLF = 'MEMBERSHIP_COUNTRY_CLUBS_GOLF';
    const CATEGORY_MEMORABILIA = 'MEMORABILIA';
    const CATEGORY_MEN_AND_BOY_CLOTHING_AND_ACCESSORY_STORES = 'MEN_AND_BOY_CLOTHING_AND_ACCESSORY_STORES';
    const CATEGORY_MEN_CLOTHING = 'MEN_CLOTHING';
    const CATEGORY_MERCHANDISE = 'MERCHANDISE';
    const CATEGORY_METAPHYSICAL = 'METAPHYSICAL';
    const CATEGORY_MILITARIA = 'MILITARIA';
    const CATEGORY_MILITARY_AND_CIVIL_SERVICE_UNIFORMS = 'MILITARY_AND_CIVIL_SERVICE_UNIFORMS';
    const CATEGORY_MISC__AUTOMOTIVE_AIRCRAFT_AND_FARM_EQUIPMENT_DEALERS = 'MISC._AUTOMOTIVE_AIRCRAFT_AND_FARM_EQUIPMENT_DEALERS';
    const CATEGORY_MISC__GENERAL_MERCHANDISE = 'MISC._GENERAL_MERCHANDISE';
    const CATEGORY_MISCELLANEOUS_GENERAL_SERVICES = 'MISCELLANEOUS_GENERAL_SERVICES';
    const CATEGORY_MISCELLANEOUS_REPAIR_SHOPS_AND_RELATED_SERVICES = 'MISCELLANEOUS_REPAIR_SHOPS_AND_RELATED_SERVICES';
    const CATEGORY_MODEL_KITS = 'MODEL_KITS';
    const CATEGORY_MONEY_TRANSFER_MEMBER_FINANCIAL_INSTITUTION = 'MONEY_TRANSFER_MEMBER_FINANCIAL_INSTITUTION';
    const CATEGORY_MONEY_TRANSFER_MERCHANT = 'MONEY_TRANSFER_MERCHANT';
    const CATEGORY_MOTION_PICTURE_THEATERS = 'MOTION_PICTURE_THEATERS';
    const CATEGORY_MOTOR_FREIGHT_CARRIERS_AND_TRUCKING = 'MOTOR_FREIGHT_CARRIERS_AND_TRUCKING';
    const CATEGORY_MOTOR_HOME_AND_RECREATIONAL_VEHICLE_RENTAL = 'MOTOR_HOME_AND_RECREATIONAL_VEHICLE_RENTAL';
    const CATEGORY_MOTOR_HOMES_DEALERS = 'MOTOR_HOMES_DEALERS';
    const CATEGORY_MOTOR_VEHICLE_SUPPLIES_AND_NEW_PARTS = 'MOTOR_VEHICLE_SUPPLIES_AND_NEW_PARTS';
    const CATEGORY_MOTORCYCLE_DEALERS = 'MOTORCYCLE_DEALERS';
    const CATEGORY_MOTORCYCLES = 'MOTORCYCLES';
    const CATEGORY_MOVIE = 'MOVIE';
    const CATEGORY_MOVIE_TICKETS = 'MOVIE_TICKETS';
    const CATEGORY_MOVING_AND_STORAGE = 'MOVING_AND_STORAGE';
    const CATEGORY_MULTI_LEVEL_MARKETING = 'MULTI_LEVEL_MARKETING';
    const CATEGORY_MUSIC_CDS_CASSETTES_AND_ALBUMS = 'MUSIC_CDS_CASSETTES_AND_ALBUMS';
    const CATEGORY_MUSIC_STORE_INSTRUMENTS_AND_SHEET_MUSIC = 'MUSIC_STORE_INSTRUMENTS_AND_SHEET_MUSIC';
    const CATEGORY_NETWORKING = 'NETWORKING';
    const CATEGORY_NEW_AGE = 'NEW_AGE';
    const CATEGORY_NEW_PARTS_AND_SUPPLIES_MOTOR_VEHICLE = 'NEW_PARTS_AND_SUPPLIES_MOTOR_VEHICLE';
    const CATEGORY_NEWS_DEALERS_AND_NEWSTANDS = 'NEWS_DEALERS_AND_NEWSTANDS';
    const CATEGORY_NON_DURABLE_GOODS = 'NON_DURABLE_GOODS';
    const CATEGORY_NON_FICTION = 'NON_FICTION';
    const CATEGORY_NON_PROFIT_POLITICAL_AND_RELIGION = 'NON_PROFIT_POLITICAL_AND_RELIGION';
    const CATEGORY_NONPROFIT = 'NONPROFIT';
    const CATEGORY_NOVELTIES = 'NOVELTIES';
    const CATEGORY_OEM_SOFTWARE = 'OEM_SOFTWARE';
    const CATEGORY_OFFICE_SUPPLIES_AND_EQUIPMENT = 'OFFICE_SUPPLIES_AND_EQUIPMENT';
    const CATEGORY_ONLINE_DATING = 'ONLINE_DATING';
    const CATEGORY_ONLINE_GAMING = 'ONLINE_GAMING';
    const CATEGORY_ONLINE_GAMING_CURRENCY = 'ONLINE_GAMING_CURRENCY';
    const CATEGORY_ONLINE_SERVICES = 'ONLINE_SERVICES';
    const CATEGORY_OOUTBOUND_TELEMARKETING_MERCH = 'OOUTBOUND_TELEMARKETING_MERCH';
    const CATEGORY_OPHTHALMOLOGISTS_OPTOMETRIST = 'OPHTHALMOLOGISTS_OPTOMETRIST';
    const CATEGORY_OPTICIANS_AND_DISPENSING = 'OPTICIANS_AND_DISPENSING';
    const CATEGORY_ORTHOPEDIC_GOODS_PROSTHETICS = 'ORTHOPEDIC_GOODS_PROSTHETICS';
    const CATEGORY_OSTEOPATHS = 'OSTEOPATHS';
    const CATEGORY_OTHER = 'OTHER';
    const CATEGORY_PACKAGE_TOUR_OPERATORS = 'PACKAGE_TOUR_OPERATORS';
    const CATEGORY_PAINTBALL = 'PAINTBALL';
    const CATEGORY_PAINTS_VARNISHES_AND_SUPPLIES = 'PAINTS_VARNISHES_AND_SUPPLIES';
    const CATEGORY_PARKING_LOTS_AND_GARAGES = 'PARKING_LOTS_AND_GARAGES';
    const CATEGORY_PARTS_AND_ACCESSORIES = 'PARTS_AND_ACCESSORIES';
    const CATEGORY_PAWN_SHOPS = 'PAWN_SHOPS';
    const CATEGORY_PAYCHECK_LENDER_OR_CASH_ADVANCE = 'PAYCHECK_LENDER_OR_CASH_ADVANCE';
    const CATEGORY_PERIPHERALS = 'PERIPHERALS';
    const CATEGORY_PERSONALIZED_GIFTS = 'PERSONALIZED_GIFTS';
    const CATEGORY_PET_SHOPS_PET_FOOD_AND_SUPPLIES = 'PET_SHOPS_PET_FOOD_AND_SUPPLIES';
    const CATEGORY_PETROLEUM_AND_PETROLEUM_PRODUCTS = 'PETROLEUM_AND_PETROLEUM_PRODUCTS';
    const CATEGORY_PETS_AND_ANIMALS = 'PETS_AND_ANIMALS';
    const CATEGORY_PHOTOFINISHING_LABORATORIES_PHOTO_DEVELOPING = 'PHOTOFINISHING_LABORATORIES_PHOTO_DEVELOPING';
    const CATEGORY_PHOTOGRAPHIC_STUDIOS_PORTRAITS = 'PHOTOGRAPHIC_STUDIOS_PORTRAITS';
    const CATEGORY_PHOTOGRAPHY = 'PHOTOGRAPHY';
    const CATEGORY_PHYSICAL_GOOD = 'PHYSICAL_GOOD';
    const CATEGORY_PICTURE_VIDEO_PRODUCTION = 'PICTURE_VIDEO_PRODUCTION';
    const CATEGORY_PIECE_GOODS_NOTIONS_AND_OTHER_DRY_GOODS = 'PIECE_GOODS_NOTIONS_AND_OTHER_DRY_GOODS';
    const CATEGORY_PLANTS_AND_SEEDS = 'PLANTS_AND_SEEDS';
    const CATEGORY_PLUMBING_AND_HEATING_EQUIPMENTS_AND_SUPPLIES = 'PLUMBING_AND_HEATING_EQUIPMENTS_AND_SUPPLIES';
    const CATEGORY_POLICE_RELATED_ITEMS = 'POLICE_RELATED_ITEMS';
    const CATEGORY_POLITICAL_ORGANIZATIONS = 'POLITICAL_ORGANIZATIONS';
    const CATEGORY_POSTAL_SERVICES_GOVERNMENT_ONLY = 'POSTAL_SERVICES_GOVERNMENT_ONLY';
    const CATEGORY_POSTERS = 'POSTERS';
    const CATEGORY_PREPAID_AND_STORED_VALUE_CARDS = 'PREPAID_AND_STORED_VALUE_CARDS';
    const CATEGORY_PRESCRIPTION_DRUGS = 'PRESCRIPTION_DRUGS';
    const CATEGORY_PROMOTIONAL_ITEMS = 'PROMOTIONAL_ITEMS';
    const CATEGORY_PUBLIC_WAREHOUSING_AND_STORAGE = 'PUBLIC_WAREHOUSING_AND_STORAGE';
    const CATEGORY_PUBLISHING_AND_PRINTING = 'PUBLISHING_AND_PRINTING';
    const CATEGORY_PUBLISHING_SERVICES = 'PUBLISHING_SERVICES';
    const CATEGORY_RADAR_DECTORS = 'RADAR_DECTORS';
    const CATEGORY_RADIO_TELEVISION_AND_STEREO_REPAIR = 'RADIO_TELEVISION_AND_STEREO_REPAIR';
    const CATEGORY_REAL_ESTATE = 'REAL_ESTATE';
    const CATEGORY_REAL_ESTATE_AGENT = 'REAL_ESTATE_AGENT';
    const CATEGORY_REAL_ESTATE_AGENTS_AND_MANAGERS_RENTALS = 'REAL_ESTATE_AGENTS_AND_MANAGERS_RENTALS';
    const CATEGORY_RELIGION_AND_SPIRITUALITY_FOR_PROFIT = 'RELIGION_AND_SPIRITUALITY_FOR_PROFIT';
    const CATEGORY_RELIGIOUS = 'RELIGIOUS';
    const CATEGORY_RELIGIOUS_ORGANIZATIONS = 'RELIGIOUS_ORGANIZATIONS';
    const CATEGORY_REMITTANCE = 'REMITTANCE';
    const CATEGORY_RENTAL_PROPERTY_MANAGEMENT = 'RENTAL_PROPERTY_MANAGEMENT';
    const CATEGORY_RESIDENTIAL = 'RESIDENTIAL';
    const CATEGORY_RETAIL = 'RETAIL';
    const CATEGORY_RETAIL_FINE_JEWELRY_AND_WATCHES = 'RETAIL_FINE_JEWELRY_AND_WATCHES';
    const CATEGORY_REUPHOLSTERY_AND_FURNITURE_REPAIR = 'REUPHOLSTERY_AND_FURNITURE_REPAIR';
    const CATEGORY_RINGS = 'RINGS';
    const CATEGORY_ROOFING_SIDING_SHEET_METAL = 'ROOFING_SIDING_SHEET_METAL';
    const CATEGORY_RUGS_AND_CARPETS = 'RUGS_AND_CARPETS';
    const CATEGORY_SCHOOLS_AND_COLLEGES = 'SCHOOLS_AND_COLLEGES';
    const CATEGORY_SCIENCE_FICTION = 'SCIENCE_FICTION';
    const CATEGORY_SCRAPBOOKING = 'SCRAPBOOKING';
    const CATEGORY_SCULPTURES = 'SCULPTURES';
    const CATEGORY_SECURITIES_BROKERS_AND_DEALERS = 'SECURITIES_BROKERS_AND_DEALERS';
    const CATEGORY_SECURITY_AND_SURVEILLANCE = 'SECURITY_AND_SURVEILLANCE';
    const CATEGORY_SECURITY_AND_SURVEILLANCE_EQUIPMENT = 'SECURITY_AND_SURVEILLANCE_EQUIPMENT';
    const CATEGORY_SECURITY_BROKERS_AND_DEALERS = 'SECURITY_BROKERS_AND_DEALERS';
    const CATEGORY_SEMINARS = 'SEMINARS';
    const CATEGORY_SERVICE_STATIONS = 'SERVICE_STATIONS';
    const CATEGORY_SERVICES = 'SERVICES';
    const CATEGORY_SEWING_NEEDLEWORK_FABRIC_AND_PIECE_GOODS_STORES = 'SEWING_NEEDLEWORK_FABRIC_AND_PIECE_GOODS_STORES';
    const CATEGORY_SHIPPING_AND_PACKING = 'SHIPPING_AND_PACKING';
    const CATEGORY_SHOE_REPAIR_HAT_CLEANING = 'SHOE_REPAIR_HAT_CLEANING';
    const CATEGORY_SHOE_STORES = 'SHOE_STORES';
    const CATEGORY_SHOES = 'SHOES';
    const CATEGORY_SNOWMOBILE_DEALERS = 'SNOWMOBILE_DEALERS';
    const CATEGORY_SOFTWARE = 'SOFTWARE';
    const CATEGORY_SPECIALTY_AND_MISC__FOOD_STORES = 'SPECIALTY_AND_MISC._FOOD_STORES';
    const CATEGORY_SPECIALTY_CLEANING_POLISHING_AND_SANITATION_PREPARATIONS = 'SPECIALTY_CLEANING_POLISHING_AND_SANITATION_PREPARATIONS';
    const CATEGORY_SPECIALTY_OR_RARE_PETS = 'SPECIALTY_OR_RARE_PETS';
    const CATEGORY_SPORT_GAMES_AND_TOYS = 'SPORT_GAMES_AND_TOYS';
    const CATEGORY_SPORTING_AND_RECREATIONAL_CAMPS = 'SPORTING_AND_RECREATIONAL_CAMPS';
    const CATEGORY_SPORTING_GOODS = 'SPORTING_GOODS';
    const CATEGORY_SPORTS_AND_OUTDOORS = 'SPORTS_AND_OUTDOORS';
    const CATEGORY_SPORTS_AND_RECREATION = 'SPORTS_AND_RECREATION';
    const CATEGORY_STAMP_AND_COIN = 'STAMP_AND_COIN';
    const CATEGORY_STATIONARY_PRINTING_AND_WRITING_PAPER = 'STATIONARY_PRINTING_AND_WRITING_PAPER';
    const CATEGORY_STENOGRAPHIC_AND_SECRETARIAL_SUPPORT_SERVICES = 'STENOGRAPHIC_AND_SECRETARIAL_SUPPORT_SERVICES';
    const CATEGORY_STOCKS_BONDS_SECURITIES_AND_RELATED_CERTIFICATES = 'STOCKS_BONDS_SECURITIES_AND_RELATED_CERTIFICATES';
    const CATEGORY_STORED_VALUE_CARDS = 'STORED_VALUE_CARDS';
    const CATEGORY_SUPPLIES = 'SUPPLIES';
    const CATEGORY_SUPPLIES_AND_TOYS = 'SUPPLIES_AND_TOYS';
    const CATEGORY_SURVEILLANCE_EQUIPMENT = 'SURVEILLANCE_EQUIPMENT';
    const CATEGORY_SWIMMING_POOLS_AND_SPAS = 'SWIMMING_POOLS_AND_SPAS';
    const CATEGORY_SWIMMING_POOLS_SALES_SUPPLIES_SERVICES = 'SWIMMING_POOLS_SALES_SUPPLIES_SERVICES';
    const CATEGORY_TAILORS_AND_ALTERATIONS = 'TAILORS_AND_ALTERATIONS';
    const CATEGORY_TAX_PAYMENTS = 'TAX_PAYMENTS';
    const CATEGORY_TAX_PAYMENTS_GOVERNMENT_AGENCIES = 'TAX_PAYMENTS_GOVERNMENT_AGENCIES';
    const CATEGORY_TAXICABS_AND_LIMOUSINES = 'TAXICABS_AND_LIMOUSINES';
    const CATEGORY_TELECOMMUNICATION_SERVICES = 'TELECOMMUNICATION_SERVICES';
    const CATEGORY_TELEPHONE_CARDS = 'TELEPHONE_CARDS';
    const CATEGORY_TELEPHONE_EQUIPMENT = 'TELEPHONE_EQUIPMENT';
    const CATEGORY_TELEPHONE_SERVICES = 'TELEPHONE_SERVICES';
    const CATEGORY_THEATER = 'THEATER';
    const CATEGORY_TIRE_RETREADING_AND_REPAIR = 'TIRE_RETREADING_AND_REPAIR';
    const CATEGORY_TOLL_OR_BRIDGE_FEES = 'TOLL_OR_BRIDGE_FEES';
    const CATEGORY_TOOLS_AND_EQUIPMENT = 'TOOLS_AND_EQUIPMENT';
    const CATEGORY_TOURIST_ATTRACTIONS_AND_EXHIBITS = 'TOURIST_ATTRACTIONS_AND_EXHIBITS';
    const CATEGORY_TOWING_SERVICE = 'TOWING_SERVICE';
    const CATEGORY_TOYS_AND_GAMES = 'TOYS_AND_GAMES';
    const CATEGORY_TRADE_AND_VOCATIONAL_SCHOOLS = 'TRADE_AND_VOCATIONAL_SCHOOLS';
    const CATEGORY_TRADEMARK_INFRINGEMENT = 'TRADEMARK_INFRINGEMENT';
    const CATEGORY_TRAILER_PARKS_AND_CAMPGROUNDS = 'TRAILER_PARKS_AND_CAMPGROUNDS';
    const CATEGORY_TRAINING_SERVICES = 'TRAINING_SERVICES';
    const CATEGORY_TRANSPORTATION_SERVICES = 'TRANSPORTATION_SERVICES';
    const CATEGORY_TRAVEL = 'TRAVEL';
    const CATEGORY_TRUCK_AND_UTILITY_TRAILER_RENTALS = 'TRUCK_AND_UTILITY_TRAILER_RENTALS';
    const CATEGORY_TRUCK_STOP = 'TRUCK_STOP';
    const CATEGORY_TYPESETTING_PLATE_MAKING_AND_RELATED_SERVICES = 'TYPESETTING_PLATE_MAKING_AND_RELATED_SERVICES';
    const CATEGORY_USED_MERCHANDISE_AND_SECONDHAND_STORES = 'USED_MERCHANDISE_AND_SECONDHAND_STORES';
    const CATEGORY_USED_PARTS_MOTOR_VEHICLE = 'USED_PARTS_MOTOR_VEHICLE';
    const CATEGORY_UTILITIES = 'UTILITIES';
    const CATEGORY_UTILITIES_ELECTRIC_GAS_WATER_SANITARY = 'UTILITIES_ELECTRIC_GAS_WATER_SANITARY';
    const CATEGORY_VARIETY_STORES = 'VARIETY_STORES';
    const CATEGORY_VEHICLE_SALES = 'VEHICLE_SALES';
    const CATEGORY_VEHICLE_SERVICE_AND_ACCESSORIES = 'VEHICLE_SERVICE_AND_ACCESSORIES';
    const CATEGORY_VIDEO_EQUIPMENT = 'VIDEO_EQUIPMENT';
    const CATEGORY_VIDEO_GAME_ARCADES_ESTABLISH = 'VIDEO_GAME_ARCADES_ESTABLISH';
    const CATEGORY_VIDEO_GAMES_AND_SYSTEMS = 'VIDEO_GAMES_AND_SYSTEMS';
    const CATEGORY_VIDEO_TAPE_RENTAL_STORES = 'VIDEO_TAPE_RENTAL_STORES';
    const CATEGORY_VINTAGE_AND_COLLECTIBLE_VEHICLES = 'VINTAGE_AND_COLLECTIBLE_VEHICLES';
    const CATEGORY_VINTAGE_AND_COLLECTIBLES = 'VINTAGE_AND_COLLECTIBLES';
    const CATEGORY_VITAMINS_AND_SUPPLEMENTS = 'VITAMINS_AND_SUPPLEMENTS';
    const CATEGORY_VOCATIONAL_AND_TRADE_SCHOOLS = 'VOCATIONAL_AND_TRADE_SCHOOLS';
    const CATEGORY_WATCH_CLOCK_AND_JEWELRY_REPAIR = 'WATCH_CLOCK_AND_JEWELRY_REPAIR';
    const CATEGORY_WEB_HOSTING_AND_DESIGN = 'WEB_HOSTING_AND_DESIGN';
    const CATEGORY_WELDING_REPAIR = 'WELDING_REPAIR';
    const CATEGORY_WHOLESALE_CLUBS = 'WHOLESALE_CLUBS';
    const CATEGORY_WHOLESALE_FLORIST_SUPPLIERS = 'WHOLESALE_FLORIST_SUPPLIERS';
    const CATEGORY_WHOLESALE_PRESCRIPTION_DRUGS = 'WHOLESALE_PRESCRIPTION_DRUGS';
    const CATEGORY_WILDLIFE_PRODUCTS = 'WILDLIFE_PRODUCTS';
    const CATEGORY_WIRE_TRANSFER = 'WIRE_TRANSFER';
    const CATEGORY_WIRE_TRANSFER_AND_MONEY_ORDER = 'WIRE_TRANSFER_AND_MONEY_ORDER';
    const CATEGORY_WOMEN_ACCESSORY_SPECIALITY = 'WOMEN_ACCESSORY_SPECIALITY';
    const CATEGORY_WOMEN_CLOTHING = 'WOMEN_CLOTHING';

    /** @var string */
    public $id;

    /** @var string */
    public $name;

    /** @var string */
    public $description;

    /** @var string */
    public $type;

    /**
     * @var string
     * The product category.
     *
     * use one of constants defined in this class to set the value:
     * @see CATEGORY_AC_REFRIGERATION_REPAIR
     * @see CATEGORY_ACADEMIC_SOFTWARE
     * @see CATEGORY_ACCESSORIES
     * @see CATEGORY_ACCOUNTING
     * @see CATEGORY_ADULT
     * @see CATEGORY_ADVERTISING
     * @see CATEGORY_AFFILIATED_AUTO_RENTAL
     * @see CATEGORY_AGENCIES
     * @see CATEGORY_AGGREGATORS
     * @see CATEGORY_AGRICULTURAL_COOPERATIVE_FOR_MAIL_ORDER
     * @see CATEGORY_AIR_CARRIERS_AIRLINES
     * @see CATEGORY_AIRLINES
     * @see CATEGORY_AIRPORTS_FLYING_FIELDS
     * @see CATEGORY_ALCOHOLIC_BEVERAGES
     * @see CATEGORY_AMUSEMENT_PARKS_CARNIVALS
     * @see CATEGORY_ANIMATION
     * @see CATEGORY_ANTIQUES
     * @see CATEGORY_APPLIANCES
     * @see CATEGORY_AQUARIAMS_SEAQUARIUMS_DOLPHINARIUMS
     * @see CATEGORY_ARCHITECTURAL_ENGINEERING_AND_SURVEYING_SERVICES
     * @see CATEGORY_ART_AND_CRAFT_SUPPLIES
     * @see CATEGORY_ART_DEALERS_AND_GALLERIES
     * @see CATEGORY_ARTIFACTS_GRAVE_RELATED_AND_NATIVE_AMERICAN_CRAFTS
     * @see CATEGORY_ARTS_AND_CRAFTS
     * @see CATEGORY_ARTS_CRAFTS_AND_COLLECTIBLES
     * @see CATEGORY_AUDIO_BOOKS
     * @see CATEGORY_AUTO_ASSOCIATIONS_CLUBS
     * @see CATEGORY_AUTO_DEALER_USED_ONLY
     * @see CATEGORY_AUTO_RENTALS
     * @see CATEGORY_AUTO_SERVICE
     * @see CATEGORY_AUTOMATED_FUEL_DISPENSERS
     * @see CATEGORY_AUTOMOBILE_ASSOCIATIONS
     * @see CATEGORY_AUTOMOTIVE
     * @see CATEGORY_AUTOMOTIVE_REPAIR_SHOPS_NON_DEALER
     * @see CATEGORY_AUTOMOTIVE_TOP_AND_BODY_SHOPS
     * @see CATEGORY_AVIATION
     * @see CATEGORY_BABIES_CLOTHING_AND_SUPPLIES
     * @see CATEGORY_BABY
     * @see CATEGORY_BANDS_ORCHESTRAS_ENTERTAINERS
     * @see CATEGORY_BARBIES
     * @see CATEGORY_BATH_AND_BODY
     * @see CATEGORY_BATTERIES
     * @see CATEGORY_BEAN_BABIES
     * @see CATEGORY_BEAUTY
     * @see CATEGORY_BEAUTY_AND_FRAGRANCES
     * @see CATEGORY_BED_AND_BATH
     * @see CATEGORY_BICYCLE_SHOPS_SALES_AND_SERVICE
     * @see CATEGORY_BICYCLES_AND_ACCESSORIES
     * @see CATEGORY_BILLIARD_POOL_ESTABLISHMENTS
     * @see CATEGORY_BOAT_DEALERS
     * @see CATEGORY_BOAT_RENTALS_AND_LEASING
     * @see CATEGORY_BOATING_SAILING_AND_ACCESSORIES
     * @see CATEGORY_BOOKS
     * @see CATEGORY_BOOKS_AND_MAGAZINES
     * @see CATEGORY_BOOKS_MANUSCRIPTS
     * @see CATEGORY_BOOKS_PERIODICALS_AND_NEWSPAPERS
     * @see CATEGORY_BOWLING_ALLEYS
     * @see CATEGORY_BULLETIN_BOARD
     * @see CATEGORY_BUS_LINE
     * @see CATEGORY_BUS_LINES_CHARTERS_TOUR_BUSES
     * @see CATEGORY_BUSINESS
     * @see CATEGORY_BUSINESS_AND_SECRETARIAL_SCHOOLS
     * @see CATEGORY_BUYING_AND_SHOPPING_SERVICES_AND_CLUBS
     * @see CATEGORY_CABLE_SATELLITE_AND_OTHER_PAY_TELEVISION_AND_RADIO_SERVICES
     * @see CATEGORY_CABLE_SATELLITE_AND_OTHER_PAY_TV_AND_RADIO
     * @see CATEGORY_CAMERA_AND_PHOTOGRAPHIC_SUPPLIES
     * @see CATEGORY_CAMERAS
     * @see CATEGORY_CAMERAS_AND_PHOTOGRAPHY
     * @see CATEGORY_CAMPER_RECREATIONAL_AND_UTILITY_TRAILER_DEALERS
     * @see CATEGORY_CAMPING_AND_OUTDOORS
     * @see CATEGORY_CAMPING_AND_SURVIVAL
     * @see CATEGORY_CAR_AND_TRUCK_DEALERS
     * @see CATEGORY_CAR_AND_TRUCK_DEALERS_USED_ONLY
     * @see CATEGORY_CAR_AUDIO_AND_ELECTRONICS
     * @see CATEGORY_CAR_RENTAL_AGENCY
     * @see CATEGORY_CATALOG_MERCHANT
     * @see CATEGORY_CATALOG_RETAIL_MERCHANT
     * @see CATEGORY_CATERING_SERVICES
     * @see CATEGORY_CHARITY
     * @see CATEGORY_CHECK_CASHIER
     * @see CATEGORY_CHILD_CARE_SERVICES
     * @see CATEGORY_CHILDREN_BOOKS
     * @see CATEGORY_CHIROPODISTS_PODIATRISTS
     * @see CATEGORY_CHIROPRACTORS
     * @see CATEGORY_CIGAR_STORES_AND_STANDS
     * @see CATEGORY_CIVIC_SOCIAL_FRATERNAL_ASSOCIATIONS
     * @see CATEGORY_CIVIL_SOCIAL_FRAT_ASSOCIATIONS
     * @see CATEGORY_CLOTHING
     * @see CATEGORY_CLOTHING_ACCESSORIES_AND_SHOES
     * @see CATEGORY_CLOTHING_RENTAL
     * @see CATEGORY_COFFEE_AND_TEA
     * @see CATEGORY_COIN_OPERATED_BANKS_AND_CASINOS
     * @see CATEGORY_COLLECTIBLES
     * @see CATEGORY_COLLECTION_AGENCY
     * @see CATEGORY_COLLEGES_AND_UNIVERSITIES
     * @see CATEGORY_COMMERCIAL_EQUIPMENT
     * @see CATEGORY_COMMERCIAL_FOOTWEAR
     * @see CATEGORY_COMMERCIAL_PHOTOGRAPHY
     * @see CATEGORY_COMMERCIAL_PHOTOGRAPHY_ART_AND_GRAPHICS
     * @see CATEGORY_COMMERCIAL_SPORTS_PROFESSIONA
     * @see CATEGORY_COMMODITIES_AND_FUTURES_EXCHANGE
     * @see CATEGORY_COMPUTER_AND_DATA_PROCESSING_SERVICES
     * @see CATEGORY_COMPUTER_HARDWARE_AND_SOFTWARE
     * @see CATEGORY_COMPUTER_MAINTENANCE_REPAIR_AND_SERVICES_NOT_ELSEWHERE_CLAS
     * @see CATEGORY_CONSTRUCTION
     * @see CATEGORY_CONSTRUCTION_MATERIALS_NOT_ELSEWHERE_CLASSIFIED
     * @see CATEGORY_CONSULTING_SERVICES
     * @see CATEGORY_CONSUMER_CREDIT_REPORTING_AGENCIES
     * @see CATEGORY_CONVALESCENT_HOMES
     * @see CATEGORY_COSMETIC_STORES
     * @see CATEGORY_COUNSELING_SERVICES_DEBT_MARRIAGE_PERSONAL
     * @see CATEGORY_COUNTERFEIT_CURRENCY_AND_STAMPS
     * @see CATEGORY_COUNTERFEIT_ITEMS
     * @see CATEGORY_COUNTRY_CLUBS
     * @see CATEGORY_COURIER_SERVICES
     * @see CATEGORY_COURIER_SERVICES_AIR_AND_GROUND_AND_FREIGHT_FORWARDERS
     * @see CATEGORY_COURT_COSTS_ALIMNY_CHILD_SUPT
     * @see CATEGORY_COURT_COSTS_INCLUDING_ALIMONY_AND_CHILD_SUPPORT_COURTS_OF_LAW
     * @see CATEGORY_CREDIT_CARDS
     * @see CATEGORY_CREDIT_UNION
     * @see CATEGORY_CULTURE_AND_RELIGION
     * @see CATEGORY_DAIRY_PRODUCTS_STORES
     * @see CATEGORY_DANCE_HALLS_STUDIOS_AND_SCHOOLS
     * @see CATEGORY_DECORATIVE
     * @see CATEGORY_DENTAL
     * @see CATEGORY_DENTISTS_AND_ORTHODONTISTS
     * @see CATEGORY_DEPARTMENT_STORES
     * @see CATEGORY_DESKTOP_PCS
     * @see CATEGORY_DEVICES
     * @see CATEGORY_DIECAST_TOYS_VEHICLES
     * @see CATEGORY_DIGITAL_GAMES
     * @see CATEGORY_DIGITAL_MEDIA_BOOKS_MOVIES_MUSIC
     * @see CATEGORY_DIRECT_MARKETING
     * @see CATEGORY_DIRECT_MARKETING_CATALOG_MERCHANT
     * @see CATEGORY_DIRECT_MARKETING_INBOUND_TELE
     * @see CATEGORY_DIRECT_MARKETING_OUTBOUND_TELE
     * @see CATEGORY_DIRECT_MARKETING_SUBSCRIPTION
     * @see CATEGORY_DISCOUNT_STORES
     * @see CATEGORY_DOOR_TO_DOOR_SALES
     * @see CATEGORY_DRAPERY_WINDOW_COVERING_AND_UPHOLSTERY
     * @see CATEGORY_DRINKING_PLACES
     * @see CATEGORY_DRUGSTORE
     * @see CATEGORY_DURABLE_GOODS
     * @see CATEGORY_ECOMMERCE_DEVELOPMENT
     * @see CATEGORY_ECOMMERCE_SERVICES
     * @see CATEGORY_EDUCATIONAL_AND_TEXTBOOKS
     * @see CATEGORY_ELECTRIC_RAZOR_STORES
     * @see CATEGORY_ELECTRICAL_AND_SMALL_APPLIANCE_REPAIR
     * @see CATEGORY_ELECTRICAL_CONTRACTORS
     * @see CATEGORY_ELECTRICAL_PARTS_AND_EQUIPMENT
     * @see CATEGORY_ELECTRONIC_CASH
     * @see CATEGORY_ELEMENTARY_AND_SECONDARY_SCHOOLS
     * @see CATEGORY_EMPLOYMENT
     * @see CATEGORY_ENTERTAINERS
     * @see CATEGORY_ENTERTAINMENT_AND_MEDIA
     * @see CATEGORY_EQUIP_TOOL_FURNITURE_AND_APPLIANCE_RENTAL_AND_LEASING
     * @see CATEGORY_ESCROW
     * @see CATEGORY_EVENT_AND_WEDDING_PLANNING
     * @see CATEGORY_EXERCISE_AND_FITNESS
     * @see CATEGORY_EXERCISE_EQUIPMENT
     * @see CATEGORY_EXTERMINATING_AND_DISINFECTING_SERVICES
     * @see CATEGORY_FABRICS_AND_SEWING
     * @see CATEGORY_FAMILY_CLOTHING_STORES
     * @see CATEGORY_FASHION_JEWELRY
     * @see CATEGORY_FAST_FOOD_RESTAURANTS
     * @see CATEGORY_FICTION_AND_NONFICTION
     * @see CATEGORY_FINANCE_COMPANY
     * @see CATEGORY_FINANCIAL_AND_INVESTMENT_ADVICE
     * @see CATEGORY_FINANCIAL_INSTITUTIONS_MERCHANDISE_AND_SERVICES
     * @see CATEGORY_FIREARM_ACCESSORIES
     * @see CATEGORY_FIREARMS_WEAPONS_AND_KNIVES
     * @see CATEGORY_FIREPLACE_AND_FIREPLACE_SCREENS
     * @see CATEGORY_FIREWORKS
     * @see CATEGORY_FISHING
     * @see CATEGORY_FLORISTS
     * @see CATEGORY_FLOWERS
     * @see CATEGORY_FOOD_DRINK_AND_NUTRITION
     * @see CATEGORY_FOOD_PRODUCTS
     * @see CATEGORY_FOOD_RETAIL_AND_SERVICE
     * @see CATEGORY_FRAGRANCES_AND_PERFUMES
     * @see CATEGORY_FREEZER_AND_LOCKER_MEAT_PROVISIONERS
     * @see CATEGORY_FUEL_DEALERS_FUEL_OIL_WOOD_AND_COAL
     * @see CATEGORY_FUEL_DEALERS_NON_AUTOMOTIVE
     * @see CATEGORY_FUNERAL_SERVICES_AND_CREMATORIES
     * @see CATEGORY_FURNISHING_AND_DECORATING
     * @see CATEGORY_FURNITURE
     * @see CATEGORY_FURRIERS_AND_FUR_SHOPS
     * @see CATEGORY_GADGETS_AND_OTHER_ELECTRONICS
     * @see CATEGORY_GAMBLING
     * @see CATEGORY_GAME_SOFTWARE
     * @see CATEGORY_GAMES
     * @see CATEGORY_GARDEN_SUPPLIES
     * @see CATEGORY_GENERAL
     * @see CATEGORY_GENERAL_CONTRACTORS
     * @see CATEGORY_GENERAL_GOVERNMENT
     * @see CATEGORY_GENERAL_SOFTWARE
     * @see CATEGORY_GENERAL_TELECOM
     * @see CATEGORY_GIFTS_AND_FLOWERS
     * @see CATEGORY_GLASS_PAINT_AND_WALLPAPER_STORES
     * @see CATEGORY_GLASSWARE_CRYSTAL_STORES
     * @see CATEGORY_GOVERNMENT
     * @see CATEGORY_GOVERNMENT_IDS_AND_LICENSES
     * @see CATEGORY_GOVERNMENT_LICENSED_ON_LINE_CASINOS_ON_LINE_GAMBLING
     * @see CATEGORY_GOVERNMENT_OWNED_LOTTERIES
     * @see CATEGORY_GOVERNMENT_SERVICES
     * @see CATEGORY_GRAPHIC_AND_COMMERCIAL_DESIGN
     * @see CATEGORY_GREETING_CARDS
     * @see CATEGORY_GROCERY_STORES_AND_SUPERMARKETS
     * @see CATEGORY_HARDWARE_AND_TOOLS
     * @see CATEGORY_HARDWARE_EQUIPMENT_AND_SUPPLIES
     * @see CATEGORY_HAZARDOUS_RESTRICTED_AND_PERISHABLE_ITEMS
     * @see CATEGORY_HEALTH_AND_BEAUTY_SPAS
     * @see CATEGORY_HEALTH_AND_NUTRITION
     * @see CATEGORY_HEALTH_AND_PERSONAL_CARE
     * @see CATEGORY_HEARING_AIDS_SALES_AND_SUPPLIES
     * @see CATEGORY_HEATING_PLUMBING_AC
     * @see CATEGORY_HIGH_RISK_MERCHANT
     * @see CATEGORY_HIRING_SERVICES
     * @see CATEGORY_HOBBIES_TOYS_AND_GAMES
     * @see CATEGORY_HOME_AND_GARDEN
     * @see CATEGORY_HOME_AUDIO
     * @see CATEGORY_HOME_DECOR
     * @see CATEGORY_HOME_ELECTRONICS
     * @see CATEGORY_HOSPITALS
     * @see CATEGORY_HOTELS_MOTELS_INNS_RESORTS
     * @see CATEGORY_HOUSEWARES
     * @see CATEGORY_HUMAN_PARTS_AND_REMAINS
     * @see CATEGORY_HUMOROUS_GIFTS_AND_NOVELTIES
     * @see CATEGORY_HUNTING
     * @see CATEGORY_IDS_LICENSES_AND_PASSPORTS
     * @see CATEGORY_ILLEGAL_DRUGS_AND_PARAPHERNALIA
     * @see CATEGORY_INDUSTRIAL
     * @see CATEGORY_INDUSTRIAL_AND_MANUFACTURING_SUPPLIES
     * @see CATEGORY_INSURANCE_AUTO_AND_HOME
     * @see CATEGORY_INSURANCE_DIRECT
     * @see CATEGORY_INSURANCE_LIFE_AND_ANNUITY
     * @see CATEGORY_INSURANCE_SALES_UNDERWRITING
     * @see CATEGORY_INSURANCE_UNDERWRITING_PREMIUMS
     * @see CATEGORY_INTERNET_AND_NETWORK_SERVICES
     * @see CATEGORY_INTRA_COMPANY_PURCHASES
     * @see CATEGORY_LABORATORIES_DENTAL_MEDICAL
     * @see CATEGORY_LANDSCAPING
     * @see CATEGORY_LANDSCAPING_AND_HORTICULTURAL_SERVICES
     * @see CATEGORY_LAUNDRY_CLEANING_SERVICES
     * @see CATEGORY_LEGAL
     * @see CATEGORY_LEGAL_SERVICES_AND_ATTORNEYS
     * @see CATEGORY_LOCAL_DELIVERY_SERVICE
     * @see CATEGORY_LOCKSMITH
     * @see CATEGORY_LODGING_AND_ACCOMMODATIONS
     * @see CATEGORY_LOTTERY_AND_CONTESTS
     * @see CATEGORY_LUGGAGE_AND_LEATHER_GOODS
     * @see CATEGORY_LUMBER_AND_BUILDING_MATERIALS
     * @see CATEGORY_MAGAZINES
     * @see CATEGORY_MAINTENANCE_AND_REPAIR_SERVICES
     * @see CATEGORY_MAKEUP_AND_COSMETICS
     * @see CATEGORY_MANUAL_CASH_DISBURSEMENTS
     * @see CATEGORY_MASSAGE_PARLORS
     * @see CATEGORY_MEDICAL
     * @see CATEGORY_MEDICAL_AND_PHARMACEUTICAL
     * @see CATEGORY_MEDICAL_CARE
     * @see CATEGORY_MEDICAL_EQUIPMENT_AND_SUPPLIES
     * @see CATEGORY_MEDICAL_SERVICES
     * @see CATEGORY_MEETING_PLANNERS
     * @see CATEGORY_MEMBERSHIP_CLUBS_AND_ORGANIZATIONS
     * @see CATEGORY_MEMBERSHIP_COUNTRY_CLUBS_GOLF
     * @see CATEGORY_MEMORABILIA
     * @see CATEGORY_MEN_AND_BOY_CLOTHING_AND_ACCESSORY_STORES
     * @see CATEGORY_MEN_CLOTHING
     * @see CATEGORY_MERCHANDISE
     * @see CATEGORY_METAPHYSICAL
     * @see CATEGORY_MILITARIA
     * @see CATEGORY_MILITARY_AND_CIVIL_SERVICE_UNIFORMS
     * @see CATEGORY_MISC__AUTOMOTIVE_AIRCRAFT_AND_FARM_EQUIPMENT_DEALERS
     * @see CATEGORY_MISC__GENERAL_MERCHANDISE
     * @see CATEGORY_MISCELLANEOUS_GENERAL_SERVICES
     * @see CATEGORY_MISCELLANEOUS_REPAIR_SHOPS_AND_RELATED_SERVICES
     * @see CATEGORY_MODEL_KITS
     * @see CATEGORY_MONEY_TRANSFER_MEMBER_FINANCIAL_INSTITUTION
     * @see CATEGORY_MONEY_TRANSFER_MERCHANT
     * @see CATEGORY_MOTION_PICTURE_THEATERS
     * @see CATEGORY_MOTOR_FREIGHT_CARRIERS_AND_TRUCKING
     * @see CATEGORY_MOTOR_HOME_AND_RECREATIONAL_VEHICLE_RENTAL
     * @see CATEGORY_MOTOR_HOMES_DEALERS
     * @see CATEGORY_MOTOR_VEHICLE_SUPPLIES_AND_NEW_PARTS
     * @see CATEGORY_MOTORCYCLE_DEALERS
     * @see CATEGORY_MOTORCYCLES
     * @see CATEGORY_MOVIE
     * @see CATEGORY_MOVIE_TICKETS
     * @see CATEGORY_MOVING_AND_STORAGE
     * @see CATEGORY_MULTI_LEVEL_MARKETING
     * @see CATEGORY_MUSIC_CDS_CASSETTES_AND_ALBUMS
     * @see CATEGORY_MUSIC_STORE_INSTRUMENTS_AND_SHEET_MUSIC
     * @see CATEGORY_NETWORKING
     * @see CATEGORY_NEW_AGE
     * @see CATEGORY_NEW_PARTS_AND_SUPPLIES_MOTOR_VEHICLE
     * @see CATEGORY_NEWS_DEALERS_AND_NEWSTANDS
     * @see CATEGORY_NON_DURABLE_GOODS
     * @see CATEGORY_NON_FICTION
     * @see CATEGORY_NON_PROFIT_POLITICAL_AND_RELIGION
     * @see CATEGORY_NONPROFIT
     * @see CATEGORY_NOVELTIES
     * @see CATEGORY_OEM_SOFTWARE
     * @see CATEGORY_OFFICE_SUPPLIES_AND_EQUIPMENT
     * @see CATEGORY_ONLINE_DATING
     * @see CATEGORY_ONLINE_GAMING
     * @see CATEGORY_ONLINE_GAMING_CURRENCY
     * @see CATEGORY_ONLINE_SERVICES
     * @see CATEGORY_OOUTBOUND_TELEMARKETING_MERCH
     * @see CATEGORY_OPHTHALMOLOGISTS_OPTOMETRIST
     * @see CATEGORY_OPTICIANS_AND_DISPENSING
     * @see CATEGORY_ORTHOPEDIC_GOODS_PROSTHETICS
     * @see CATEGORY_OSTEOPATHS
     * @see CATEGORY_OTHER
     * @see CATEGORY_PACKAGE_TOUR_OPERATORS
     * @see CATEGORY_PAINTBALL
     * @see CATEGORY_PAINTS_VARNISHES_AND_SUPPLIES
     * @see CATEGORY_PARKING_LOTS_AND_GARAGES
     * @see CATEGORY_PARTS_AND_ACCESSORIES
     * @see CATEGORY_PAWN_SHOPS
     * @see CATEGORY_PAYCHECK_LENDER_OR_CASH_ADVANCE
     * @see CATEGORY_PERIPHERALS
     * @see CATEGORY_PERSONALIZED_GIFTS
     * @see CATEGORY_PET_SHOPS_PET_FOOD_AND_SUPPLIES
     * @see CATEGORY_PETROLEUM_AND_PETROLEUM_PRODUCTS
     * @see CATEGORY_PETS_AND_ANIMALS
     * @see CATEGORY_PHOTOFINISHING_LABORATORIES_PHOTO_DEVELOPING
     * @see CATEGORY_PHOTOGRAPHIC_STUDIOS_PORTRAITS
     * @see CATEGORY_PHOTOGRAPHY
     * @see CATEGORY_PHYSICAL_GOOD
     * @see CATEGORY_PICTURE_VIDEO_PRODUCTION
     * @see CATEGORY_PIECE_GOODS_NOTIONS_AND_OTHER_DRY_GOODS
     * @see CATEGORY_PLANTS_AND_SEEDS
     * @see CATEGORY_PLUMBING_AND_HEATING_EQUIPMENTS_AND_SUPPLIES
     * @see CATEGORY_POLICE_RELATED_ITEMS
     * @see CATEGORY_POLITICAL_ORGANIZATIONS
     * @see CATEGORY_POSTAL_SERVICES_GOVERNMENT_ONLY
     * @see CATEGORY_POSTERS
     * @see CATEGORY_PREPAID_AND_STORED_VALUE_CARDS
     * @see CATEGORY_PRESCRIPTION_DRUGS
     * @see CATEGORY_PROMOTIONAL_ITEMS
     * @see CATEGORY_PUBLIC_WAREHOUSING_AND_STORAGE
     * @see CATEGORY_PUBLISHING_AND_PRINTING
     * @see CATEGORY_PUBLISHING_SERVICES
     * @see CATEGORY_RADAR_DECTORS
     * @see CATEGORY_RADIO_TELEVISION_AND_STEREO_REPAIR
     * @see CATEGORY_REAL_ESTATE
     * @see CATEGORY_REAL_ESTATE_AGENT
     * @see CATEGORY_REAL_ESTATE_AGENTS_AND_MANAGERS_RENTALS
     * @see CATEGORY_RELIGION_AND_SPIRITUALITY_FOR_PROFIT
     * @see CATEGORY_RELIGIOUS
     * @see CATEGORY_RELIGIOUS_ORGANIZATIONS
     * @see CATEGORY_REMITTANCE
     * @see CATEGORY_RENTAL_PROPERTY_MANAGEMENT
     * @see CATEGORY_RESIDENTIAL
     * @see CATEGORY_RETAIL
     * @see CATEGORY_RETAIL_FINE_JEWELRY_AND_WATCHES
     * @see CATEGORY_REUPHOLSTERY_AND_FURNITURE_REPAIR
     * @see CATEGORY_RINGS
     * @see CATEGORY_ROOFING_SIDING_SHEET_METAL
     * @see CATEGORY_RUGS_AND_CARPETS
     * @see CATEGORY_SCHOOLS_AND_COLLEGES
     * @see CATEGORY_SCIENCE_FICTION
     * @see CATEGORY_SCRAPBOOKING
     * @see CATEGORY_SCULPTURES
     * @see CATEGORY_SECURITIES_BROKERS_AND_DEALERS
     * @see CATEGORY_SECURITY_AND_SURVEILLANCE
     * @see CATEGORY_SECURITY_AND_SURVEILLANCE_EQUIPMENT
     * @see CATEGORY_SECURITY_BROKERS_AND_DEALERS
     * @see CATEGORY_SEMINARS
     * @see CATEGORY_SERVICE_STATIONS
     * @see CATEGORY_SERVICES
     * @see CATEGORY_SEWING_NEEDLEWORK_FABRIC_AND_PIECE_GOODS_STORES
     * @see CATEGORY_SHIPPING_AND_PACKING
     * @see CATEGORY_SHOE_REPAIR_HAT_CLEANING
     * @see CATEGORY_SHOE_STORES
     * @see CATEGORY_SHOES
     * @see CATEGORY_SNOWMOBILE_DEALERS
     * @see CATEGORY_SOFTWARE
     * @see CATEGORY_SPECIALTY_AND_MISC__FOOD_STORES
     * @see CATEGORY_SPECIALTY_CLEANING_POLISHING_AND_SANITATION_PREPARATIONS
     * @see CATEGORY_SPECIALTY_OR_RARE_PETS
     * @see CATEGORY_SPORT_GAMES_AND_TOYS
     * @see CATEGORY_SPORTING_AND_RECREATIONAL_CAMPS
     * @see CATEGORY_SPORTING_GOODS
     * @see CATEGORY_SPORTS_AND_OUTDOORS
     * @see CATEGORY_SPORTS_AND_RECREATION
     * @see CATEGORY_STAMP_AND_COIN
     * @see CATEGORY_STATIONARY_PRINTING_AND_WRITING_PAPER
     * @see CATEGORY_STENOGRAPHIC_AND_SECRETARIAL_SUPPORT_SERVICES
     * @see CATEGORY_STOCKS_BONDS_SECURITIES_AND_RELATED_CERTIFICATES
     * @see CATEGORY_STORED_VALUE_CARDS
     * @see CATEGORY_SUPPLIES
     * @see CATEGORY_SUPPLIES_AND_TOYS
     * @see CATEGORY_SURVEILLANCE_EQUIPMENT
     * @see CATEGORY_SWIMMING_POOLS_AND_SPAS
     * @see CATEGORY_SWIMMING_POOLS_SALES_SUPPLIES_SERVICES
     * @see CATEGORY_TAILORS_AND_ALTERATIONS
     * @see CATEGORY_TAX_PAYMENTS
     * @see CATEGORY_TAX_PAYMENTS_GOVERNMENT_AGENCIES
     * @see CATEGORY_TAXICABS_AND_LIMOUSINES
     * @see CATEGORY_TELECOMMUNICATION_SERVICES
     * @see CATEGORY_TELEPHONE_CARDS
     * @see CATEGORY_TELEPHONE_EQUIPMENT
     * @see CATEGORY_TELEPHONE_SERVICES
     * @see CATEGORY_THEATER
     * @see CATEGORY_TIRE_RETREADING_AND_REPAIR
     * @see CATEGORY_TOLL_OR_BRIDGE_FEES
     * @see CATEGORY_TOOLS_AND_EQUIPMENT
     * @see CATEGORY_TOURIST_ATTRACTIONS_AND_EXHIBITS
     * @see CATEGORY_TOWING_SERVICE
     * @see CATEGORY_TOYS_AND_GAMES
     * @see CATEGORY_TRADE_AND_VOCATIONAL_SCHOOLS
     * @see CATEGORY_TRADEMARK_INFRINGEMENT
     * @see CATEGORY_TRAILER_PARKS_AND_CAMPGROUNDS
     * @see CATEGORY_TRAINING_SERVICES
     * @see CATEGORY_TRANSPORTATION_SERVICES
     * @see CATEGORY_TRAVEL
     * @see CATEGORY_TRUCK_AND_UTILITY_TRAILER_RENTALS
     * @see CATEGORY_TRUCK_STOP
     * @see CATEGORY_TYPESETTING_PLATE_MAKING_AND_RELATED_SERVICES
     * @see CATEGORY_USED_MERCHANDISE_AND_SECONDHAND_STORES
     * @see CATEGORY_USED_PARTS_MOTOR_VEHICLE
     * @see CATEGORY_UTILITIES
     * @see CATEGORY_UTILITIES_ELECTRIC_GAS_WATER_SANITARY
     * @see CATEGORY_VARIETY_STORES
     * @see CATEGORY_VEHICLE_SALES
     * @see CATEGORY_VEHICLE_SERVICE_AND_ACCESSORIES
     * @see CATEGORY_VIDEO_EQUIPMENT
     * @see CATEGORY_VIDEO_GAME_ARCADES_ESTABLISH
     * @see CATEGORY_VIDEO_GAMES_AND_SYSTEMS
     * @see CATEGORY_VIDEO_TAPE_RENTAL_STORES
     * @see CATEGORY_VINTAGE_AND_COLLECTIBLE_VEHICLES
     * @see CATEGORY_VINTAGE_AND_COLLECTIBLES
     * @see CATEGORY_VITAMINS_AND_SUPPLEMENTS
     * @see CATEGORY_VOCATIONAL_AND_TRADE_SCHOOLS
     * @see CATEGORY_WATCH_CLOCK_AND_JEWELRY_REPAIR
     * @see CATEGORY_WEB_HOSTING_AND_DESIGN
     * @see CATEGORY_WELDING_REPAIR
     * @see CATEGORY_WHOLESALE_CLUBS
     * @see CATEGORY_WHOLESALE_FLORIST_SUPPLIERS
     * @see CATEGORY_WHOLESALE_PRESCRIPTION_DRUGS
     * @see CATEGORY_WILDLIFE_PRODUCTS
     * @see CATEGORY_WIRE_TRANSFER
     * @see CATEGORY_WIRE_TRANSFER_AND_MONEY_ORDER
     * @see CATEGORY_WOMEN_ACCESSORY_SPECIALITY
     * @see CATEGORY_WOMEN_CLOTHING
     */
    public $category;

    /** @var string */
    public $image_url;

    /** @var string */
    public $home_url;
}
