<?php

/**
 * This file is part of OXID eSales Paypal module.
 *
 * OXID eSales Paypal module is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OXID eSales Paypal module is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OXID eSales Paypal module.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @copyright (C) OXID eSales AG 2003-2020
 */
$sLangName = 'Deutsch';

$aLang = [
    'charset'                        => 'UTF-8',
    'paypal'                         => 'PayPal',
    'OXPS_PAYPAL_ACTIONS'            => 'Aktionen',
    'OXPS_PAYPAL_CAPTURE_PAYMENT'    => 'Zahlung erfassen',
    'OXPS_PAYPAL_CAPTURE'            => 'Erfassung',
    'OXPS_PAYPAL_ISSUE_REFUND'       => 'Rückerstattung ausstellen',
    'OXPS_PAYPAL_REFUND'             => 'Rückerstattung',
    'OXPS_PAYPAL_SHOW_BALANCE_AFFECTING_RECORDS' => 'Nur das Gleichgewicht beeinflusst',
    'OXPS_PAYPAL_REPORT_REFERENCE'   => 'Referenz melden',
    'OXPS_PAYPAL_TRANSACTION_TO_PRICE' => 'Preis bis',
    'OXPS_PAYPAL_TRANSACTION_FROM_PRICE' => 'Preis von',
    'OXPS_PAYPAL_AVAILABLE_BALANCE'  => 'Verfügbar',
    'OXPS_PAYPAL_WITHHELD_BALANCE'   => 'Zurückgehalten',
    'OXPS_PAYPAL_TOTAL_BALANCE'      => 'Gesamt',
    'OXPS_PAYPAL_PRIMARY'            => 'Primär',
    'OXPS_PAYPAL_MORE'               => 'Mehr',
    'OXPS_PAYPAL_LAST_REFRESH_TIME'  => 'Letzte Aktualisierung',
    'OXPS_PAYPAL_CURRENCY_CODE'      => 'Währungscode',
    'OXPS_PAYPAL_AS_OF_TIME'         => 'Ab der zeit',
    'OXPS_PAYPAL_PAYMENT_INSTRUMENT_CREDIT_CARD' => 'Kreditkarte',
    'OXPS_PAYPAL_PAYMENT_INSTRUMENT_DEBIT_CARD'  => 'Debitkarte',
    'OXPS_PAYPAL_TRANSACTION_STATUS_P' => 'Ausstehend',
    'OXPS_PAYPAL_TRANSACTION_STATUS_F' => 'Teilweise erstattet',
    'OXPS_PAYPAL_TRANSACTION_STATUS_D' => 'Verweigert',
    'OXPS_PAYPAL_TRANSACTION_STATUS_S' => 'Abgeschlossen',
    'OXPS_PAYPAL_TRANSACTION_STATUS_V' => 'Erstattet',
    'OXPS_PAYPAL_DATE_SELECT_HELP'   => 'Maximal 31 Tage erlaubt!',
    'OXPS_PAYPAL_APPLY'              => 'Anwenden',
    'OXPS_PAYPAL_TRANSACTION_DATE_FROM' => 'Stammen aus',
    'OXPS_PAYPAL_TRANSACTION_DATE_TO'   => 'Datum bis',
    'OXPS_PAYPAL_TRANSACTION_TYPE'   => 'Transaktionstyp',
    'OXPS_PAYPAL_TERMINAL_ID'        => 'Terminal ID',
    'OXPS_PAYPAL_PAYMENT_INSTRUMENT_TYPE' => 'Instrumententyp',
    'OXPS_PAYPAL_TRANSACTION_CURRENCY' => 'Transaktionswährung',
    'OXPS_PAYPAL_TRANSACTION_AMOUNT' => 'Transaktionsbetrag',
    'OXPS_PAYPAL_TRANSACTION_DATE'   => 'Transaktionsdatum',
    'OXPS_PAYPAL_STORE_ID'           => 'Store ID',
    'OXPS_PAYPAL_ACCOUNT_ID'         => 'Konto-ID',
    'OXPS_PAYPAL_TRANSACTION_ID'     => 'Transaktions-ID',
    'OXPS_PAYPAL_REFERENCE_ID'       => 'Referenz-ID',
    'OXPS_PAYPAL_REFERENCE_ID_TYPE'  => 'Referenz-ID-Typ',
    'OXPS_PAYPAL_EVENT_CODE'         => 'Ereigniscode',
    'OXPS_PAYPAL_INITIATION_DATE'    => 'Initiationsdatum',
    'OXPS_PAYPAL_UPDATED_DATE'       => 'Aktualisierungsdatum',
    'OXPS_PAYPAL_TRANSACTION_NOTE'   => 'Hinweis',
    'OXPS_PAYPAL_BANK_REFERENCE_ID'  => 'Bankreferenz-ID',
    'OXPS_PAYPAL_INVOICE_ID'         => 'Rechnungs-ID',
    'OXPS_PAYPAL_CUSTOM_FIELD'       => 'Benutzerdefiniertes Feld',
    'OXPS_PAYPAL_CREDIT_TERM'        => 'Kreditlaufzeit',
    'OXPS_PAYPAL_INSTRUMENT_TYPE'    => 'Instrumententyp',
    'OXPS_PAYPAL_TRANSACTION_STATUS' => 'Status',
    'OXPS_PAYPAL_PAYMENT_TRACKING_ID' => 'Zahlungsverfolgungs-ID',
    'OXPS_PAYPAL_PAYMENT_METHOD_TYPE' => 'Zahlungsmethode Typ',
    'OXPS_PAYPAL_INSTRUMENT_SUB_TYPE' => 'Instrument Sub Type',
    'OXPS_PAYPAL_TRANSACTION_SUBJECT' => 'Betreff',
    'OXPS_PAYPAL_PROTECTION_ELIGIBILITY' => 'Schutzberechtigung',
    'tbclorder_paypal'               => 'PayPal',
    // Paypal Config
    'OXPS_PAYPAL_CONFIG'             => 'Konfiguration',
    'OXPS_PAYPAL_SUBSCRIBE'          => 'PayPal Abos',
    'PAYPAL_SUBSCRIBE_MAIN'          => 'PayPal Abos',
    'OXPS_PAYPAL_TRANSACTIONS'       => 'Transaktionen',
    'OXPS_PAYPAL_BALANCES'           => 'Guthaben',
    'OXPS_PAYPAL_GENERAL'            => 'Allgemein',
    'OXPS_PAYPAL_WEBHOOK_ID'         => 'Webhook ID',
    'OXPS_PAYPAL_OPMODE'             => 'Betriebsmodus',
    'OXPS_PAYPAL_OPMODE_LIVE'        => 'Live',
    'OXPS_PAYPAL_OPMODE_SANDBOX'     => 'Sandbox',
    'OXPS_PAYPAL_CLIENT_ID'          => 'Client ID',
    'OXPS_PAYPAL_CLIENT_SECRET'      => 'Secret',
    'OXPS_PAYPAL_CREDENTIALS'        => 'API Anmeldeinformationen',
    'OXPS_PAYPAL_WEBHOOK_TITLE'      => 'Webhooks',
    'OXPS_PAYPAL_WEBHOOK_URL'        => 'Oxid Webhook URL',
    'HELP_OXPS_PAYPAL_WEBHOOK_URL'   => 'Tragen Sie diese URL für den Webhook im Paypal Portal ein.',
    'OXPS_PAYPAL_LIVE_CREDENTIALS'   => 'Live API Anmeldeinformationen',
    'OXPS_PAYPAL_SANDBOX_CREDENTIALS'        => 'Sandbox API Anmeldeinformationen',
    'OXPS_PAYPAL_LIVE_BUTTON_CREDENTIALS'    => 'Anmeldung Händler Paypal-Integration (Live)',
    'OXPS_PAYPAL_SANDBOX_BUTTON_CREDENTIALS' => 'Anmeldung Händler Paypal-Integration (Sandbox)',
    'OXPS_PAYPAL_ERR_CONF_INVALID'   =>
        'Ein oder mehrere Konfigurationswerte sind entweder nicht festgelegt oder falsch. Bitte überprüfen Sie sie noch einmal.<br>
        <b>Modul inaktiv.</b>',
    'OXPS_PAYPAL_CONF_VALID'         => 'Konfigurationswerte OK.<br><b>Modul ist aktiv</b>',
    'OXPS_PAYPAL_BUTTON_PLACEMEMT_TITLE' => 'Einstellungen für die Tastenplatzierung',
    'OXPS_PAYPAL_PRODUCT_DETAILS_BUTTON_PLACEMENT' => 'Produktdetailseite',
    'OXPS_PAYPAL_ADD_TO_BASKET_MODAL_PLACEMENT' => 'Modal in den Warenkorb legen',
    'OXPS_PAYPAL_MINI_BASKET_BUTTON_PLACEMENT' => 'Minikorb',
    'HELP_OXPS_PAYPAL_BUTTON_PLACEMEMT' => 'Schalten Sie die Anzeige der PayPal-Schaltflächen um',
    'HELP_OXPS_PAYPAL_CREDENTIALS'   =>
        'Wenn Sie die API Anmeldeinformationen bereits vorleigen haben, können Sie sie direkt eingeben.<br>
        Alternativ nutzen Sie einen der folgenden Links um die API Anmeldeinformationen für den Live oder den Sandbox-Modus zu erzeugen.',
    'HELP_OXPS_PAYPAL_CLIENT_ID'     => 'Client ID des Live-Account für live-Modus',
    'HELP_OXPS_PAYPAL_CLIENT_SECRET' => 'Secret des Live-Account für live-Modus',
    'HELP_OXPS_PAYPAL_SANDBOX_CLIENT_ID'     => 'Client ID des Sandbox-Account für Sandbox-Modus',
    'HELP_OXPS_PAYPAL_SANDBOX_CLIENT_SECRET' => 'Secret des Sandbox-Account für Sandbox-Modus',
    'HELP_OXPS_PAYPAL_OPMODE'        => 'Verwenden Sie Sandbox (Test), um PayPal zu konfigurieren und zu testen. Wenn Sie bereit sind,
        echte Transaktionen zu empfangen, wechseln Sie zu Produktion (live).',
    'OXPS_PAYPAL_WEBHOOK_ID_HELP'    => 'Die ID des Webhooks, wie in Ihrem Developer Portal-Konto konfiguriert',
    // Paypal ORDER
    'OEPAYPAL_AMOUNT'                      => 'Betrag',
    'OEPAYPAL_SHOP_PAYMENT_STATUS'         => 'Shop-Zahlungsstatus',
    'OEPAYPAL_ORDER_PRICE'                 => 'Bestellpreis gesamt',
    'OEPAYPAL_ORDER_PRODUCTS'              => 'Bestellte Artikel',
    'OEPAYPAL_CAPTURED'                    => 'Eingezogen',
    'OEPAYPAL_REFUNDED'                    => 'Erstattet',
    'OEPAYPAL_CAPTURED_NET'                => 'Resultierender Zahlungsbetrag',
    'OEPAYPAL_CAPTURED_AMOUNT'             => 'Eingezogener Betrag',
    'OEPAYPAL_REFUNDED_AMOUNT'             => 'Erstatteter Betrag',
    'OEPAYPAL_VOIDED_AMOUNT'               => 'Stornierter Betrag',
    'OEPAYPAL_MONEY_CAPTURE'               => 'Geldeinzug',
    'OEPAYPAL_MONEY_REFUND'                => 'Gelderstattung',
    'OEPAYPAL_CAPTURE'                     => 'Einziehen',
    'OEPAYPAL_REFUND'                      => 'Erstatten',
    'OEPAYPAL_DETAILS'                     => 'Details',
    'OEPAYPAL_AUTHORIZATION'               => 'Autorisierung',
    'OEPAYPAL_CANCEL_AUTHORIZATION'        => 'Stornieren',
    'OEPAYPAL_PAYMENT_HISTORY'             => 'PayPal-Historie',
    'OEPAYPAL_HISTORY_DATE'                => 'Datum',
    'OEPAYPAL_HISTORY_ACTION'              => 'Aktion',
    'OEPAYPAL_HISTORY_PAYPAL_STATUS'       => 'PayPal-Status',
    'OEPAYPAL_HISTORY_PAYPAL_STATUS_HELP'  => 'Von PayPal zurückgegebener Zahlungsstatus. Für mehr Details siehe (nur Englisch): <a href="https://www.paypal.com/webapps/helpcenter/article/?articleID=94021&m=SRE" target="_blank" >PayPal Zahlungsstatus</a>',
    'OEPAYPAL_HISTORY_COMMENT'             => 'Kommentar',
    'OEPAYPAL_HISTORY_ACTIONS'             => 'Aktionen',
    'OEPAYPAL_HISTORY_NOTICE'              => 'Hinweis',
    'OEPAYPAL_HISTORY_NOTICE_TEXT'         => 'Im Fehlerfall siehe "Details" für mehr Informationen',
    'OEPAYPAL_MONEY_ACTION_FULL'           => 'vollständig',
    'OEPAYPAL_MONEY_ACTION_PARTIAL'        => 'teilweise',
    'OEPAYPAL_LIST_STATUS_ALL'             => 'Alle',
    'OEPAYPAL_STATUS_CREATED'              => 'erstellt',
    'OEPAYPAL_STATUS_SAVED'                => 'gespeichert',
    'OEPAYPAL_STATUS_APPROVED'             => 'genehmigt',
    'OEPAYPAL_STATUS_VOIDED'               => 'Ungültig',
    'OEPAYPAL_STATUS_COMPLETED'            => 'abgeschlossen',
    'OEPAYPAL_STATUS_PAYER_ACTION_REQUIRED'=> 'Käufer Aktion erforderlich',
    'OEPAYPAL_STATUS_PARTIALLY_COMPLETED'  => 'teilweise abgeschlossen',
    'OEPAYPAL_PAYMENT_METHOD'              => 'Zahlungsart',
    'OEPAYPAL_CLOSE'                       => 'Schließen',
    'OEPAYPAL_COMMENT'                     => 'Kommentar',
    'OEPAYPAL_RESPONSE_FROM_PAYPAL'        => 'Fehlermeldung von PayPal: ',
    'OEPAYPAL_AUTHORIZATIONID'             => 'Autorisierungs-ID',
    'OEPAYPAL_TRANSACTIONID'               => 'Transaktions-ID',
    'OEPAYPAL_CORRELATIONID'               => 'Korrelations-ID',
    'OXPS_PAYPAL_REFUND_AMOUNT'            => 'Rückerstattungsbetrag',
    'OXPS_PAYPAL_INVOICE_ID'               => 'Rechnungs-ID',
    'OXPS_PAYPAL_NOTE_TO_BUYER'            => 'Hinweis für Käufer',
    'OXPS_PAYPAL_REFUND_ALL'               => 'Alle erstatten',
];
