<?php

/**
 * This file is part of OXID eSales Paypal module.
 *
 * OXID eSales Paypal module is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OXID eSales Paypal module is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OXID eSales Paypal module.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @copyright (C) OXID eSales AG 2003-2020
 */
$sLangName = 'Deutsch';

//TODO
$aLang = [
    'charset' => 'UTF-8',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T00' => 'PayPal account-to-PayPal account payment',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T01' => 'Non-payment-related fees',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T02' => 'Currency conversion',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T03' => 'Bank deposit into PayPal account',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T04' => 'Bank withdrawal from PayPal account',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T05' => 'Debit card',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T06' => 'Credit card withdrawal',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T07' => 'Credit card deposit',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T08' => 'Bonus',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T09' => 'Incentive',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T10' => 'Bill pay',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T11' => 'Reversal',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T12' => 'Adjustment',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T13' => 'Authorization',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T14' => 'Dividend',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T15' => 'Hold for dispute or other investigation',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T16' => 'Buyer credit deposit',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T17' => 'Non-bank withdrawal',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T18' => 'Buyer credit withdrawal',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T19' => 'Account correction',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T20' => 'Funds transfer from PayPal account to another',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T21' => 'Reserves and releases',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T22' => 'Transfers',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T30' => 'Generic instrument and Open Wallet',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T50' => 'Collections and disbursements',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T97' => 'Payables and receivables',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T98' => 'Display only transaction',
    'OXPS_PAYPAL_TRANSACTION_TYPE_GROUP_T99' => 'Other',

    'OXPS_PAYPAL_TRANSACTION_TYPE_T0000' => 'General received payment ',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0001' => 'MassPay payment',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0002' => 'Subscription payment',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0003' => 'Pre-approved payment',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0004' => 'eBay auction payment',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0005' => 'Direct payment API',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0006' => 'PayPal Checkout APIs',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0007' => 'Website payments standard payment',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0008' => 'Postage payment to carrier',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0009' => 'Gift certificate payment',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0010' => 'Third-party auction payment',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0011' => 'Mobile payment',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0012' => 'Virtual terminal payment',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0013' => 'Donation payment',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0014' => 'Rebate payments',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0015' => 'Third-party payout',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0016' => 'Third-party recoupment',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0017' => 'Store-to-store transfers',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0018' => 'PayPal Here payment',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0019' => 'Generic instrument-funded payment',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0100' => 'General',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0101' => 'Website payments',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0102' => 'Foreign bank withdrawal fee',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0103' => 'WorldLink check withdrawal fee',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0104' => 'Mass payment batch fee',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0105' => 'Check withdrawal',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0106' => 'Chargeback processing fee',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0107' => 'Payment fee',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0108' => 'ATM withdrawal',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0109' => 'Auto-sweep from account',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0110' => 'International credit card withdrawal',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0111' => 'Warranty fee for warranty purchase',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0112' => 'Gift certificate expiration fee',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0113' => 'Partner fee',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0200' => 'General currency conversion',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0201' => 'User-initiated currency conversion',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0202' => 'Currency conversion required to cover negative balance',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0300' => 'General funding of PayPal account',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0301' => 'PayPal balance manager funding of PayPal account',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0302' => 'ACH funding for funds recovery from account balance',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0303' => 'Electronic funds transfer (EFT)',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0400' => 'General withdrawal from PayPal account',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0401' => 'AutoSweep',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0500' => 'General PayPal debit card transaction',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0501' => 'Virtual PayPal debit card transaction',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0502' => 'PayPal debit card withdrawal to ATM',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0503' => 'Hidden virtual PayPal debit card transaction',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0504' => 'PayPal debit card cash advance',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0505' => 'PayPal debit authorization',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0600' => 'General credit card withdrawal',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0700' => 'General credit card deposit',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0701' => 'Credit card deposit for negative PayPal account balance',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0800' => 'General',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0801' => 'Debit card cash back bonus',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0802' => 'Merchant referral account bonus',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0803' => 'Balance manager account bonus',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0804' => 'PayPal buyer warranty bonus',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0805' => 'PayPal protection bonus, payout for PayPal buyer protection, payout for full protection with PayPal buyer credit',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0806' => 'Bonus for first ACH use',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0807' => 'Credit card security charge refund',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0808' => 'Credit card cash back bonus',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0900' => 'General incentive or certificate redemption',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0901' => 'Gift certificate redemption',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0902' => 'Points incentive redemption',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0903' => 'Coupon redemption',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0904' => 'eBay loyalty incentive',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T0905' => 'Offers used as funding source',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1000' => 'Bill pay transaction',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1100' => 'General reversal',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1101' => 'Reversal of ACH withdrawal transaction',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1102' => 'Reversal of debit card transaction',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1103' => 'Reversal of points usage',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1104' => 'Reversal of ACH deposit',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1105' => 'Reversal of general account hold',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1106' => 'Payment reversal, initiated by PayPal',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1107' => 'Payment refund, initiated by merchant',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1108' => 'Fee reversal',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1109' => 'Fee refund',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1110' => 'Hold for dispute investigation',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1111' => 'Cancellation of hold for dispute resolution',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1112' => 'MAM reversal',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1113' => 'Non-reference credit payment',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1114' => 'MassPay reversal transaction',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1115' => 'MassPay refund transaction',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1116' => 'Instant payment review (IPR) reversal',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1117' => 'Rebate or cash back reversal',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1118' => 'Generic instrument/Open Wallet reversals (seller side)',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1119' => 'Generic instrument/Open Wallet reversals (buyer side)',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1200' => 'General account adjustment',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1201' => 'Chargeback',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1202' => 'Chargeback reversal',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1203' => 'Charge-off adjustment',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1204' => 'Incentive adjustment',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1205' => 'Reimbursement of chargeback',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1207' => 'Chargeback re-presentment rejection',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1208' => 'Chargeback cancellation',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1300' => 'General authorization',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1301' => 'Reauthorization',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1302' => 'Void of authorization',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1400' => 'General dividend',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1500' => 'General temporary hold',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1501' => 'Account hold for open authorization',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1502' => 'Account hold for ACH deposit',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1503' => 'Temporary hold on available balance',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1600' => 'PayPal buyer credit payment funding',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1601' => 'BML credit',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1602' => 'Buyer credit payment',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1603' => 'Buyer credit payment withdrawal',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1700' => 'General withdrawal to non-bank institution',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1701' => 'WorldLink withdrawal',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1800' => 'General buyer credit payment',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1801' => 'BML withdrawal',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T1900' => 'General adjustment without business-related event',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T2000' => 'General intra-account transfer',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T2001' => 'Settlement consolidation',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T2002' => 'Transfer of funds from payable',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T2003' => 'Transfer to external GL entity',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T2101' => 'General hold',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T2102' => 'General hold release',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T2103' => 'Reserve hold',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T2104' => 'Reserve release',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T2105' => 'Payment review hold',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T2106' => 'Payment review release',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T2107' => 'Payment hold',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T2108' => 'Payment hold release',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T2109' => 'Gift certificate purchase',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T2110' => 'Gift certificate redemption',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T2111' => 'Funds not yet available',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T2112' => 'Funds available',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T2113' => 'Blocked payments',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T2201' => 'Transfer to and from a credit-card-funded restricted balance',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T3000' => 'Generic instrument/Open Wallet transaction',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T5000' => 'Deferred disbursement',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T5001' => 'Delayed disbursement',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T9700' => 'Account receivable for shipping',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T9701' => 'Funds payable',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T9702' => 'Funds receivable',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T9800' => 'Display only transaction',
    'OXPS_PAYPAL_TRANSACTION_TYPE_T9900' => 'Other'
];