name: oxid module tests

on:
  push:
    branches:
      - '*'
      - '!b-6.1.x'

jobs:
  install:
    strategy:
      matrix:
        php: [ 7.4 ]
        oxid: [ 6.3 ]
    runs-on: ubuntu-latest
    container:
      image: oxidprojects/oxid-apache-php:oxid${{ matrix.oxid }}-php${{ matrix.php }}
      options: --tmpfs=/build:noatime
    env:
      MODULE_NAME: oxid-solution-catalysts/paypal-module
    steps:
      - uses: actions/checkout@v3

      - name: install
        run: composer create-project oxid-professional-services/test-oxid /build/oxid dev-oxid${{matrix.oxid}} --no-interaction -s dev --repository="{\"url\":\"https://github.com/keywan-ghadami-oxid/test-oxid.git\", \"type\":\"vcs\"}" --remove-vcs

      - name: move artifacts to projects folder
        run: |
          mkdir -p /build/oxid/project-modules/module-under-test && cp -r * /build/oxid/project-modules/module-under-test

      - name: set latest tag as env
        run: |
          echo "TAG=$(cat LATEST_CLIENT_TAG)" >> $GITHUB_ENV

      - name: Checkout paypal-client repo
        uses: actions/checkout@v3
        with:
          repository: OXID-eSales/paypal-client
          ref: ${{ env.TAG }}
          path: paypal-client

      - name: move paypal-client to projects folder
        run: |
          cp -r paypal-client/ /build/oxid/project-modules/

      - name: add project module folder
        run:
          composer config repositories.build path /build/oxid/project-modules/\*
        working-directory: /build/oxid

      - name: require module
        run: composer require --no-interaction $MODULE_NAME
        working-directory: /build/oxid

      - name: move config to source folder
        run: cp config.inc.php-dist source/config.inc.php
        working-directory: /build/oxid

      - name: zip temp artifact
        run: tar czf /build/oxid.tar.gz --directory /build oxid

      - name: Upload oxid-with-deps
        uses: actions/upload-artifact@v3
        with:
          name: oxid${{ matrix.oxid }}-php${{ matrix.php }}-with-deps
          path: /build/oxid.tar.gz

  static_code_checks:
    strategy:
      matrix:
        php: [ 7.4 ]
        oxid: [ 6.3 ]
    runs-on: ubuntu-latest
    needs: install
    container:
      image: oxidprojects/oxid-apache-php:oxid${{ matrix.oxid }}-php${{ matrix.php }}
      options: --tmpfs=/build:exec,noatime
    steps:
      - name: Download oxid installation
        uses: actions/download-artifact@v3
        with:
          name: oxid${{ matrix.oxid }}-php${{ matrix.php }}-with-deps
          path: /build
      - name: extract oxid installation
        run: |
          tar xzf oxid.tar.gz
        working-directory: /build/

      - name: prepare autoload
        run: composer update
        working-directory: /build/oxid/vendor/oxid-solution-catalysts/paypal-module/

      - name: run psalm
        run: composer psalm-report
        working-directory: /build/oxid/vendor/oxid-solution-catalysts/paypal-module/

      - name: Save psalm logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: psalm-log
          path: /build/oxid/vendor/oxid-solution-catalysts/paypal-module/logs/psalm.sonarqube.json

  codestyle_checks:
    strategy:
      matrix:
        php: [ 7.4 ]
        oxid: [ 6.3 ]
    runs-on: ubuntu-latest
    needs: install
    container:
      image: oxidprojects/oxid-apache-php:oxid${{ matrix.oxid }}-php${{ matrix.php }}
    steps:
      - name: Download oxid installation
        uses: actions/download-artifact@v3
        with:
          name: oxid${{ matrix.oxid }}-php${{ matrix.php }}-with-deps
          path: /build
      - name: extract oxid installation
        run: |
          tar xzf oxid.tar.gz
        working-directory: /build/

      - name: prepare autoload
        run: composer update
        working-directory: /build/oxid/vendor/oxid-solution-catalysts/paypal-module/

      - name: run phpcs
        run: composer phpcs
        working-directory: /build/oxid/vendor/oxid-solution-catalysts/paypal-module/

  oxid_unit_tests:
    strategy:
      matrix:
        php: [ 7.4 ]
        oxid: [ 6.3 ]
    runs-on: ubuntu-latest
    needs: install
    env:
      MYSQL_DATABASE: oxid
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      SHOP_URL: http://localhost/
    services:
      db:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: oxid
        ports:
          - 3306
        options: --tmpfs=/tmp:noatime --tmpfs=/var/lib/mysql:noatime --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    container:
      image: oxidprojects/oxid-apache-php:oxid${{ matrix.oxid }}-php${{ matrix.php }}
      options: --tmpfs=/build:exec,noatime
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: oxid${{ matrix.oxid }}-php${{ matrix.php }}-with-deps
          path: /build
      - name: extract temp artifact
        run: |
          tar xzf oxid.tar.gz
        working-directory: /build/

      - name: mysql shema
        run: mysql -u $MYSQL_USER -h db -p$MYSQL_PASSWORD $MYSQL_DATABASE < "vendor/oxid-esales/oxideshop-ce/source/Setup/Sql/database_schema.sql"
        working-directory: /build/oxid

      - name: mysql data
        run: mysql -u $MYSQL_USER -h db -p$MYSQL_PASSWORD $MYSQL_DATABASE < "vendor/oxid-esales/oxideshop-ce/source/Setup/Sql/initial_data.sql"
        working-directory: /build/oxid

      - name: console
        run: vendor/bin/oe-console oe:module:install-configuration source/modules/osc/paypal/
        working-directory: /build/oxid

      - name: console
        run: vendor/bin/oe-console oe:module:apply-configuration
        working-directory: /build/oxid

      - name: console
        run: vendor/bin/oe-eshop-db_migrate migrations:migrate
        working-directory: /build/oxid

      - name: console
        run: vendor/bin/oe-eshop-db_views_generate
        working-directory: /build/oxid

      - name: console
        run: vendor/bin/oe-console oe:module:activate osc-paypal
        working-directory: /build/oxid

      - name: check mod config
        run: cat var/configuration/shops/1.yaml
        working-directory: /build/oxid

      - name: composer validate
        run: composer validate
        working-directory: /build/oxid

      - name: oxid config
        run: cat source/config.inc.php
        working-directory: /build/oxid

      - name: run unit tests
        run: |
          XDEBUG_MODE=coverage php vendor/bin/phpunit \
            --bootstrap vendor/oxid-esales/testing-library/bootstrap.php \
            -c /build/oxid/vendor/oxid-solution-catalysts/paypal-module/Tests/phpunit.xml \
            --coverage-clover=/build/oxid/logs/clover.xml \
            --coverage-text \
            --log-junit /build/oxid/logs/phpunit.xml
        working-directory: /build/oxid

      - name: Save logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: /build/oxid/logs

  oxid_codeception_tests:
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4' ]
    needs: [ install_shop_with_module ]
    runs-on: self-hosted
    steps:
      - name: Load current installation from cache
        uses: actions/cache@v2
        with:
          path: |
            ./*
          key: development-${{ matrix.php }}-${{ github.run_number }}-${{ github.run_attempt }}
          restore-keys: |
            development-${{ matrix.php }}-${{ github.run_number }}-${{ github.run_attempt }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Start containers
        run: |
          make up
          sleep 2

      - name: Install codeception dependencies
        run: |
          docker-compose exec -T php composer require codeception/module-rest:^1.4.2 --dev --no-update
          docker-compose exec -T php composer require codeception/module-phpbrowser:^1.0.2 --dev --no-update
          docker-compose exec -T php composer update

      - name: Run tests
        run: |
          docker-compose exec -T \
            -e PARTIAL_MODULE_PATHS=osc\paypal \
            -e ACTIVATE_ALL_MODULES=1 \
            -e RUN_TESTS_FOR_SHOP=0 \
            -e RUN_TESTS_FOR_MODULES=0 \
            -e ADDITIONAL_TEST_PATHS='/var/www/vendor//oxid-solution-catalysts/paypal-module/Tests' \
            php php vendor/bin/runtests-codeception

      - name: Stop containers
        if: always()
        run: |
          docker-compose down
          sleep 2

      - name: Upload log artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: CodeceptionTestsLog-${{ matrix.php }}
          path: |
            source/vendor/${{ env.PACKAGE_NAME }}/Tests/Codeception/_output/
            source/source/log/oxideshop.log
            source/source/log/unzer/
            source/data/php/logs/error_log.txt

  sonarcloud:
    needs: [oxid_unit_tests, static_code_checks]
    runs-on: ubuntu-latest
    if: always() && (needs.oxid_unit_tests.result != 'failure')
    steps:
      - name: Checkout module
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: List
        run: |
          pwd
          ls -alh

      - name: Load phpunit logs
        uses: actions/download-artifact@v3
        with:
          name: logs
          path: logs

      - name: Load psalm logs
        uses: actions/download-artifact@v3
        with:
          name: psalm-log
          path: logs/

      - name: Fix phpunit logs
        run: |
          ls -alh logs
          sed -i 's+/build/oxid/project-modules/module-under-test/++gI' logs/clover.xml
          sed -i 's+/build/oxid/project-modules/module-under-test/++gI' logs/phpunit.xml

      - name: Save logs
        uses: actions/upload-artifact@v3
        with:
          name: logs-adjusted
          path: logs

      - name: Show logs
        run: |
          ls -alh logs
          cat logs/clover.xml
          cat logs/phpunit.xml
          cat logs/psalm.sonarqube.json

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.sources=src
            -Dsonar.tests=Tests
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.php.coverage.reportPaths=logs/clover.xml
            -Dsonar.php.tests.reportPath=logs/phpunit.xml
            -Dsonar.php.psalm.reportPaths=logs/psalm.sonarqube.json
            -Dsonar.cpd.php.minimumTokens=30
            -Dsonar.cpd.php.minimumLines=6
